// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"srv.exe.dev/ent/facility"
)

// Facility is the model entity for the Facility schema.
type Facility struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Municipality holds the value of the "municipality" field.
	Municipality string `json:"municipality,omitempty"`
	// ScraperType holds the value of the "scraper_type" field.
	ScraperType string `json:"scraper_type,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FacilityQuery when eager-loading is set.
	Edges        FacilityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FacilityEdges holds the relations/edges for other nodes in the graph.
type FacilityEdges struct {
	// WatchConditions holds the value of the watch_conditions edge.
	WatchConditions []*WatchCondition `json:"watch_conditions,omitempty"`
	// Slots holds the value of the slots edge.
	Slots []*Slot `json:"slots,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// WatchConditionsOrErr returns the WatchConditions value or an error if the edge
// was not loaded in eager-loading.
func (e FacilityEdges) WatchConditionsOrErr() ([]*WatchCondition, error) {
	if e.loadedTypes[0] {
		return e.WatchConditions, nil
	}
	return nil, &NotLoadedError{edge: "watch_conditions"}
}

// SlotsOrErr returns the Slots value or an error if the edge
// was not loaded in eager-loading.
func (e FacilityEdges) SlotsOrErr() ([]*Slot, error) {
	if e.loadedTypes[1] {
		return e.Slots, nil
	}
	return nil, &NotLoadedError{edge: "slots"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Facility) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case facility.FieldEnabled:
			values[i] = new(sql.NullBool)
		case facility.FieldID, facility.FieldName, facility.FieldMunicipality, facility.FieldScraperType, facility.FieldURL:
			values[i] = new(sql.NullString)
		case facility.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Facility fields.
func (_m *Facility) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case facility.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case facility.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case facility.FieldMunicipality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field municipality", values[i])
			} else if value.Valid {
				_m.Municipality = value.String
			}
		case facility.FieldScraperType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scraper_type", values[i])
			} else if value.Valid {
				_m.ScraperType = value.String
			}
		case facility.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case facility.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case facility.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Facility.
// This includes values selected through modifiers, order, etc.
func (_m *Facility) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWatchConditions queries the "watch_conditions" edge of the Facility entity.
func (_m *Facility) QueryWatchConditions() *WatchConditionQuery {
	return NewFacilityClient(_m.config).QueryWatchConditions(_m)
}

// QuerySlots queries the "slots" edge of the Facility entity.
func (_m *Facility) QuerySlots() *SlotQuery {
	return NewFacilityClient(_m.config).QuerySlots(_m)
}

// Update returns a builder for updating this Facility.
// Note that you need to call Facility.Unwrap() before calling this method if this Facility
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Facility) Update() *FacilityUpdateOne {
	return NewFacilityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Facility entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Facility) Unwrap() *Facility {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Facility is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Facility) String() string {
	var builder strings.Builder
	builder.WriteString("Facility(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("municipality=")
	builder.WriteString(_m.Municipality)
	builder.WriteString(", ")
	builder.WriteString("scraper_type=")
	builder.WriteString(_m.ScraperType)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Facilities is a parsable slice of Facility.
type Facilities []*Facility
