// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/facility"
	"srv.exe.dev/ent/slot"
	"srv.exe.dev/ent/watchcondition"
)

// FacilityCreate is the builder for creating a Facility entity.
type FacilityCreate struct {
	config
	mutation *FacilityMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *FacilityCreate) SetName(v string) *FacilityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetMunicipality sets the "municipality" field.
func (_c *FacilityCreate) SetMunicipality(v string) *FacilityCreate {
	_c.mutation.SetMunicipality(v)
	return _c
}

// SetScraperType sets the "scraper_type" field.
func (_c *FacilityCreate) SetScraperType(v string) *FacilityCreate {
	_c.mutation.SetScraperType(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *FacilityCreate) SetURL(v string) *FacilityCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *FacilityCreate) SetEnabled(v bool) *FacilityCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *FacilityCreate) SetNillableEnabled(v *bool) *FacilityCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FacilityCreate) SetCreatedAt(v time.Time) *FacilityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FacilityCreate) SetNillableCreatedAt(v *time.Time) *FacilityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FacilityCreate) SetID(v string) *FacilityCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddWatchConditionIDs adds the "watch_conditions" edge to the WatchCondition entity by IDs.
func (_c *FacilityCreate) AddWatchConditionIDs(ids ...string) *FacilityCreate {
	_c.mutation.AddWatchConditionIDs(ids...)
	return _c
}

// AddWatchConditions adds the "watch_conditions" edges to the WatchCondition entity.
func (_c *FacilityCreate) AddWatchConditions(v ...*WatchCondition) *FacilityCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWatchConditionIDs(ids...)
}

// AddSlotIDs adds the "slots" edge to the Slot entity by IDs.
func (_c *FacilityCreate) AddSlotIDs(ids ...string) *FacilityCreate {
	_c.mutation.AddSlotIDs(ids...)
	return _c
}

// AddSlots adds the "slots" edges to the Slot entity.
func (_c *FacilityCreate) AddSlots(v ...*Slot) *FacilityCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSlotIDs(ids...)
}

// Mutation returns the FacilityMutation object of the builder.
func (_c *FacilityCreate) Mutation() *FacilityMutation {
	return _c.mutation
}

// Save creates the Facility in the database.
func (_c *FacilityCreate) Save(ctx context.Context) (*Facility, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FacilityCreate) SaveX(ctx context.Context) *Facility {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FacilityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FacilityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FacilityCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := facility.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := facility.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FacilityCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Facility.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := facility.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Facility.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Municipality(); !ok {
		return &ValidationError{Name: "municipality", err: errors.New(`ent: missing required field "Facility.municipality"`)}
	}
	if v, ok := _c.mutation.Municipality(); ok {
		if err := facility.MunicipalityValidator(v); err != nil {
			return &ValidationError{Name: "municipality", err: fmt.Errorf(`ent: validator failed for field "Facility.municipality": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScraperType(); !ok {
		return &ValidationError{Name: "scraper_type", err: errors.New(`ent: missing required field "Facility.scraper_type"`)}
	}
	if v, ok := _c.mutation.ScraperType(); ok {
		if err := facility.ScraperTypeValidator(v); err != nil {
			return &ValidationError{Name: "scraper_type", err: fmt.Errorf(`ent: validator failed for field "Facility.scraper_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Facility.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := facility.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Facility.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Facility.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Facility.created_at"`)}
	}
	return nil
}

func (_c *FacilityCreate) sqlSave(ctx context.Context) (*Facility, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Facility.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FacilityCreate) createSpec() (*Facility, *sqlgraph.CreateSpec) {
	var (
		_node = &Facility{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(facility.Table, sqlgraph.NewFieldSpec(facility.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(facility.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Municipality(); ok {
		_spec.SetField(facility.FieldMunicipality, field.TypeString, value)
		_node.Municipality = value
	}
	if value, ok := _c.mutation.ScraperType(); ok {
		_spec.SetField(facility.FieldScraperType, field.TypeString, value)
		_node.ScraperType = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(facility.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(facility.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(facility.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.WatchConditionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   facility.WatchConditionsTable,
			Columns: []string{facility.WatchConditionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(watchcondition.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SlotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   facility.SlotsTable,
			Columns: []string{facility.SlotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(slot.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FacilityCreateBulk is the builder for creating many Facility entities in bulk.
type FacilityCreateBulk struct {
	config
	err      error
	builders []*FacilityCreate
}

// Save creates the Facility entities in the database.
func (_c *FacilityCreateBulk) Save(ctx context.Context) ([]*Facility, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Facility, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FacilityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FacilityCreateBulk) SaveX(ctx context.Context) []*Facility {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FacilityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FacilityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
