// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/ground"
	"srv.exe.dev/ent/municipality"
	"srv.exe.dev/ent/predicate"
	"srv.exe.dev/ent/slot"
)

// GroundQuery is the builder for querying Ground entities.
type GroundQuery struct {
	config
	ctx              *QueryContext
	order            []ground.OrderOption
	inters           []Interceptor
	predicates       []predicate.Ground
	withMunicipality *MunicipalityQuery
	withSlots        *SlotQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroundQuery builder.
func (_q *GroundQuery) Where(ps ...predicate.Ground) *GroundQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GroundQuery) Limit(limit int) *GroundQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GroundQuery) Offset(offset int) *GroundQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GroundQuery) Unique(unique bool) *GroundQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GroundQuery) Order(o ...ground.OrderOption) *GroundQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMunicipality chains the current query on the "municipality" edge.
func (_q *GroundQuery) QueryMunicipality() *MunicipalityQuery {
	query := (&MunicipalityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ground.Table, ground.FieldID, selector),
			sqlgraph.To(municipality.Table, municipality.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ground.MunicipalityTable, ground.MunicipalityColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySlots chains the current query on the "slots" edge.
func (_q *GroundQuery) QuerySlots() *SlotQuery {
	query := (&SlotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ground.Table, ground.FieldID, selector),
			sqlgraph.To(slot.Table, slot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ground.SlotsTable, ground.SlotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Ground entity from the query.
// Returns a *NotFoundError when no Ground was found.
func (_q *GroundQuery) First(ctx context.Context) (*Ground, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ground.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GroundQuery) FirstX(ctx context.Context) *Ground {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Ground ID from the query.
// Returns a *NotFoundError when no Ground ID was found.
func (_q *GroundQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ground.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GroundQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Ground entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Ground entity is found.
// Returns a *NotFoundError when no Ground entities are found.
func (_q *GroundQuery) Only(ctx context.Context) (*Ground, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ground.Label}
	default:
		return nil, &NotSingularError{ground.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GroundQuery) OnlyX(ctx context.Context) *Ground {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Ground ID in the query.
// Returns a *NotSingularError when more than one Ground ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GroundQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ground.Label}
	default:
		err = &NotSingularError{ground.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GroundQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Grounds.
func (_q *GroundQuery) All(ctx context.Context) ([]*Ground, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Ground, *GroundQuery]()
	return withInterceptors[[]*Ground](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GroundQuery) AllX(ctx context.Context) []*Ground {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Ground IDs.
func (_q *GroundQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(ground.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GroundQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GroundQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GroundQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GroundQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GroundQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GroundQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroundQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GroundQuery) Clone() *GroundQuery {
	if _q == nil {
		return nil
	}
	return &GroundQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]ground.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Ground{}, _q.predicates...),
		withMunicipality: _q.withMunicipality.Clone(),
		withSlots:        _q.withSlots.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMunicipality tells the query-builder to eager-load the nodes that are connected to
// the "municipality" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroundQuery) WithMunicipality(opts ...func(*MunicipalityQuery)) *GroundQuery {
	query := (&MunicipalityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMunicipality = query
	return _q
}

// WithSlots tells the query-builder to eager-load the nodes that are connected to
// the "slots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroundQuery) WithSlots(opts ...func(*SlotQuery)) *GroundQuery {
	query := (&SlotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSlots = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MunicipalityID string `json:"municipality_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Ground.Query().
//		GroupBy(ground.FieldMunicipalityID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GroundQuery) GroupBy(field string, fields ...string) *GroundGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroundGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = ground.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MunicipalityID string `json:"municipality_id,omitempty"`
//	}
//
//	client.Ground.Query().
//		Select(ground.FieldMunicipalityID).
//		Scan(ctx, &v)
func (_q *GroundQuery) Select(fields ...string) *GroundSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GroundSelect{GroundQuery: _q}
	sbuild.label = ground.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GroundSelect configured with the given aggregations.
func (_q *GroundQuery) Aggregate(fns ...AggregateFunc) *GroundSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GroundQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !ground.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GroundQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Ground, error) {
	var (
		nodes       = []*Ground{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMunicipality != nil,
			_q.withSlots != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Ground).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Ground{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMunicipality; query != nil {
		if err := _q.loadMunicipality(ctx, query, nodes, nil,
			func(n *Ground, e *Municipality) { n.Edges.Municipality = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSlots; query != nil {
		if err := _q.loadSlots(ctx, query, nodes,
			func(n *Ground) { n.Edges.Slots = []*Slot{} },
			func(n *Ground, e *Slot) { n.Edges.Slots = append(n.Edges.Slots, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GroundQuery) loadMunicipality(ctx context.Context, query *MunicipalityQuery, nodes []*Ground, init func(*Ground), assign func(*Ground, *Municipality)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Ground)
	for i := range nodes {
		fk := nodes[i].MunicipalityID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(municipality.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "municipality_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroundQuery) loadSlots(ctx context.Context, query *SlotQuery, nodes []*Ground, init func(*Ground), assign func(*Ground, *Slot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Ground)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(slot.FieldGroundID)
	}
	query.Where(predicate.Slot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ground.SlotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GroundID
		if fk == nil {
			return fmt.Errorf(`foreign-key "ground_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ground_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *GroundQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GroundQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ground.Table, ground.Columns, sqlgraph.NewFieldSpec(ground.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ground.FieldID)
		for i := range fields {
			if fields[i] != ground.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withMunicipality != nil {
			_spec.Node.AddColumnOnce(ground.FieldMunicipalityID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GroundQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(ground.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = ground.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroundGroupBy is the group-by builder for Ground entities.
type GroundGroupBy struct {
	selector
	build *GroundQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GroundGroupBy) Aggregate(fns ...AggregateFunc) *GroundGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GroundGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroundQuery, *GroundGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GroundGroupBy) sqlScan(ctx context.Context, root *GroundQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GroundSelect is the builder for selecting fields of Ground entities.
type GroundSelect struct {
	*GroundQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GroundSelect) Aggregate(fns ...AggregateFunc) *GroundSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GroundSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroundQuery, *GroundSelect](ctx, _s.GroundQuery, _s, _s.inters, v)
}

func (_s *GroundSelect) sqlScan(ctx context.Context, root *GroundQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
