// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"srv.exe.dev/ent/ground"
	"srv.exe.dev/ent/municipality"
)

// Ground is the model entity for the Ground schema.
type Ground struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CourtPattern holds the value of the "court_pattern" field.
	CourtPattern string `json:"court_pattern,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroundQuery when eager-loading is set.
	Edges                GroundEdges `json:"edges"`
	municipality_grounds *string
	selectValues         sql.SelectValues
}

// GroundEdges holds the relations/edges for other nodes in the graph.
type GroundEdges struct {
	// Municipality holds the value of the municipality edge.
	Municipality *Municipality `json:"municipality,omitempty"`
	// Slots holds the value of the slots edge.
	Slots []*Slot `json:"slots,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MunicipalityOrErr returns the Municipality value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroundEdges) MunicipalityOrErr() (*Municipality, error) {
	if e.Municipality != nil {
		return e.Municipality, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: municipality.Label}
	}
	return nil, &NotLoadedError{edge: "municipality"}
}

// SlotsOrErr returns the Slots value or an error if the edge
// was not loaded in eager-loading.
func (e GroundEdges) SlotsOrErr() ([]*Slot, error) {
	if e.loadedTypes[1] {
		return e.Slots, nil
	}
	return nil, &NotLoadedError{edge: "slots"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ground) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ground.FieldEnabled:
			values[i] = new(sql.NullBool)
		case ground.FieldID, ground.FieldName, ground.FieldCourtPattern:
			values[i] = new(sql.NullString)
		case ground.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case ground.ForeignKeys[0]: // municipality_grounds
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ground fields.
func (_m *Ground) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ground.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ground.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case ground.FieldCourtPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field court_pattern", values[i])
			} else if value.Valid {
				_m.CourtPattern = value.String
			}
		case ground.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case ground.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ground.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field municipality_grounds", values[i])
			} else if value.Valid {
				_m.municipality_grounds = new(string)
				*_m.municipality_grounds = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ground.
// This includes values selected through modifiers, order, etc.
func (_m *Ground) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMunicipality queries the "municipality" edge of the Ground entity.
func (_m *Ground) QueryMunicipality() *MunicipalityQuery {
	return NewGroundClient(_m.config).QueryMunicipality(_m)
}

// QuerySlots queries the "slots" edge of the Ground entity.
func (_m *Ground) QuerySlots() *SlotQuery {
	return NewGroundClient(_m.config).QuerySlots(_m)
}

// Update returns a builder for updating this Ground.
// Note that you need to call Ground.Unwrap() before calling this method if this Ground
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ground) Update() *GroundUpdateOne {
	return NewGroundClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ground entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ground) Unwrap() *Ground {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ground is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ground) String() string {
	var builder strings.Builder
	builder.WriteString("Ground(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("court_pattern=")
	builder.WriteString(_m.CourtPattern)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Grounds is a parsable slice of Ground.
type Grounds []*Ground
