// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/ground"
	"srv.exe.dev/ent/municipality"
	"srv.exe.dev/ent/predicate"
	"srv.exe.dev/ent/scrapejob"
	"srv.exe.dev/ent/slot"
)

// MunicipalityQuery is the builder for querying Municipality entities.
type MunicipalityQuery struct {
	config
	ctx            *QueryContext
	order          []municipality.OrderOption
	inters         []Interceptor
	predicates     []predicate.Municipality
	withGrounds    *GroundQuery
	withSlots      *SlotQuery
	withScrapeJobs *ScrapeJobQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MunicipalityQuery builder.
func (_q *MunicipalityQuery) Where(ps ...predicate.Municipality) *MunicipalityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MunicipalityQuery) Limit(limit int) *MunicipalityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MunicipalityQuery) Offset(offset int) *MunicipalityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MunicipalityQuery) Unique(unique bool) *MunicipalityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MunicipalityQuery) Order(o ...municipality.OrderOption) *MunicipalityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGrounds chains the current query on the "grounds" edge.
func (_q *MunicipalityQuery) QueryGrounds() *GroundQuery {
	query := (&GroundClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(municipality.Table, municipality.FieldID, selector),
			sqlgraph.To(ground.Table, ground.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, municipality.GroundsTable, municipality.GroundsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySlots chains the current query on the "slots" edge.
func (_q *MunicipalityQuery) QuerySlots() *SlotQuery {
	query := (&SlotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(municipality.Table, municipality.FieldID, selector),
			sqlgraph.To(slot.Table, slot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, municipality.SlotsTable, municipality.SlotsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScrapeJobs chains the current query on the "scrape_jobs" edge.
func (_q *MunicipalityQuery) QueryScrapeJobs() *ScrapeJobQuery {
	query := (&ScrapeJobClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(municipality.Table, municipality.FieldID, selector),
			sqlgraph.To(scrapejob.Table, scrapejob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, municipality.ScrapeJobsTable, municipality.ScrapeJobsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Municipality entity from the query.
// Returns a *NotFoundError when no Municipality was found.
func (_q *MunicipalityQuery) First(ctx context.Context) (*Municipality, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{municipality.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MunicipalityQuery) FirstX(ctx context.Context) *Municipality {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Municipality ID from the query.
// Returns a *NotFoundError when no Municipality ID was found.
func (_q *MunicipalityQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{municipality.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MunicipalityQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Municipality entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Municipality entity is found.
// Returns a *NotFoundError when no Municipality entities are found.
func (_q *MunicipalityQuery) Only(ctx context.Context) (*Municipality, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{municipality.Label}
	default:
		return nil, &NotSingularError{municipality.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MunicipalityQuery) OnlyX(ctx context.Context) *Municipality {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Municipality ID in the query.
// Returns a *NotSingularError when more than one Municipality ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MunicipalityQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{municipality.Label}
	default:
		err = &NotSingularError{municipality.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MunicipalityQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Municipalities.
func (_q *MunicipalityQuery) All(ctx context.Context) ([]*Municipality, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Municipality, *MunicipalityQuery]()
	return withInterceptors[[]*Municipality](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MunicipalityQuery) AllX(ctx context.Context) []*Municipality {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Municipality IDs.
func (_q *MunicipalityQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(municipality.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MunicipalityQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MunicipalityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MunicipalityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MunicipalityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MunicipalityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MunicipalityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MunicipalityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MunicipalityQuery) Clone() *MunicipalityQuery {
	if _q == nil {
		return nil
	}
	return &MunicipalityQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]municipality.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.Municipality{}, _q.predicates...),
		withGrounds:    _q.withGrounds.Clone(),
		withSlots:      _q.withSlots.Clone(),
		withScrapeJobs: _q.withScrapeJobs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGrounds tells the query-builder to eager-load the nodes that are connected to
// the "grounds" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MunicipalityQuery) WithGrounds(opts ...func(*GroundQuery)) *MunicipalityQuery {
	query := (&GroundClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrounds = query
	return _q
}

// WithSlots tells the query-builder to eager-load the nodes that are connected to
// the "slots" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MunicipalityQuery) WithSlots(opts ...func(*SlotQuery)) *MunicipalityQuery {
	query := (&SlotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSlots = query
	return _q
}

// WithScrapeJobs tells the query-builder to eager-load the nodes that are connected to
// the "scrape_jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MunicipalityQuery) WithScrapeJobs(opts ...func(*ScrapeJobQuery)) *MunicipalityQuery {
	query := (&ScrapeJobClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScrapeJobs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Municipality.Query().
//		GroupBy(municipality.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MunicipalityQuery) GroupBy(field string, fields ...string) *MunicipalityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MunicipalityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = municipality.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Municipality.Query().
//		Select(municipality.FieldName).
//		Scan(ctx, &v)
func (_q *MunicipalityQuery) Select(fields ...string) *MunicipalitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MunicipalitySelect{MunicipalityQuery: _q}
	sbuild.label = municipality.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MunicipalitySelect configured with the given aggregations.
func (_q *MunicipalityQuery) Aggregate(fns ...AggregateFunc) *MunicipalitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MunicipalityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !municipality.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MunicipalityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Municipality, error) {
	var (
		nodes       = []*Municipality{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withGrounds != nil,
			_q.withSlots != nil,
			_q.withScrapeJobs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Municipality).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Municipality{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGrounds; query != nil {
		if err := _q.loadGrounds(ctx, query, nodes,
			func(n *Municipality) { n.Edges.Grounds = []*Ground{} },
			func(n *Municipality, e *Ground) { n.Edges.Grounds = append(n.Edges.Grounds, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSlots; query != nil {
		if err := _q.loadSlots(ctx, query, nodes,
			func(n *Municipality) { n.Edges.Slots = []*Slot{} },
			func(n *Municipality, e *Slot) { n.Edges.Slots = append(n.Edges.Slots, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withScrapeJobs; query != nil {
		if err := _q.loadScrapeJobs(ctx, query, nodes,
			func(n *Municipality) { n.Edges.ScrapeJobs = []*ScrapeJob{} },
			func(n *Municipality, e *ScrapeJob) { n.Edges.ScrapeJobs = append(n.Edges.ScrapeJobs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MunicipalityQuery) loadGrounds(ctx context.Context, query *GroundQuery, nodes []*Municipality, init func(*Municipality), assign func(*Municipality, *Ground)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Municipality)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ground.FieldMunicipalityID)
	}
	query.Where(predicate.Ground(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(municipality.GroundsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MunicipalityID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "municipality_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MunicipalityQuery) loadSlots(ctx context.Context, query *SlotQuery, nodes []*Municipality, init func(*Municipality), assign func(*Municipality, *Slot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Municipality)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(slot.FieldMunicipalityID)
	}
	query.Where(predicate.Slot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(municipality.SlotsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MunicipalityID
		if fk == nil {
			return fmt.Errorf(`foreign-key "municipality_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "municipality_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MunicipalityQuery) loadScrapeJobs(ctx context.Context, query *ScrapeJobQuery, nodes []*Municipality, init func(*Municipality), assign func(*Municipality, *ScrapeJob)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Municipality)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(scrapejob.FieldMunicipalityID)
	}
	query.Where(predicate.ScrapeJob(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(municipality.ScrapeJobsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MunicipalityID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "municipality_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MunicipalityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MunicipalityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(municipality.Table, municipality.Columns, sqlgraph.NewFieldSpec(municipality.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, municipality.FieldID)
		for i := range fields {
			if fields[i] != municipality.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MunicipalityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(municipality.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = municipality.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MunicipalityGroupBy is the group-by builder for Municipality entities.
type MunicipalityGroupBy struct {
	selector
	build *MunicipalityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MunicipalityGroupBy) Aggregate(fns ...AggregateFunc) *MunicipalityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MunicipalityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MunicipalityQuery, *MunicipalityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MunicipalityGroupBy) sqlScan(ctx context.Context, root *MunicipalityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MunicipalitySelect is the builder for selecting fields of Municipality entities.
type MunicipalitySelect struct {
	*MunicipalityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MunicipalitySelect) Aggregate(fns ...AggregateFunc) *MunicipalitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MunicipalitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MunicipalityQuery, *MunicipalitySelect](ctx, _s.MunicipalityQuery, _s, _s.inters, v)
}

func (_s *MunicipalitySelect) sqlScan(ctx context.Context, root *MunicipalityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
