// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/predicate"
	"srv.exe.dev/ent/promocode"
	"srv.exe.dev/ent/promocodeusage"
)

// PromoCodeUpdate is the builder for updating PromoCode entities.
type PromoCodeUpdate struct {
	config
	hooks    []Hook
	mutation *PromoCodeMutation
}

// Where appends a list predicates to the PromoCodeUpdate builder.
func (_u *PromoCodeUpdate) Where(ps ...predicate.PromoCode) *PromoCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *PromoCodeUpdate) SetCode(v string) *PromoCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableCode(v *string) *PromoCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDiscountType sets the "discount_type" field.
func (_u *PromoCodeUpdate) SetDiscountType(v promocode.DiscountType) *PromoCodeUpdate {
	_u.mutation.SetDiscountType(v)
	return _u
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableDiscountType(v *promocode.DiscountType) *PromoCodeUpdate {
	if v != nil {
		_u.SetDiscountType(*v)
	}
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *PromoCodeUpdate) SetDiscountValue(v int) *PromoCodeUpdate {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableDiscountValue(v *int) *PromoCodeUpdate {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *PromoCodeUpdate) AddDiscountValue(v int) *PromoCodeUpdate {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// SetAppliesTo sets the "applies_to" field.
func (_u *PromoCodeUpdate) SetAppliesTo(v string) *PromoCodeUpdate {
	_u.mutation.SetAppliesTo(v)
	return _u
}

// SetNillableAppliesTo sets the "applies_to" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableAppliesTo(v *string) *PromoCodeUpdate {
	if v != nil {
		_u.SetAppliesTo(*v)
	}
	return _u
}

// ClearAppliesTo clears the value of the "applies_to" field.
func (_u *PromoCodeUpdate) ClearAppliesTo() *PromoCodeUpdate {
	_u.mutation.ClearAppliesTo()
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *PromoCodeUpdate) SetValidFrom(v time.Time) *PromoCodeUpdate {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableValidFrom(v *time.Time) *PromoCodeUpdate {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// SetValidUntil sets the "valid_until" field.
func (_u *PromoCodeUpdate) SetValidUntil(v time.Time) *PromoCodeUpdate {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableValidUntil(v *time.Time) *PromoCodeUpdate {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// ClearValidUntil clears the value of the "valid_until" field.
func (_u *PromoCodeUpdate) ClearValidUntil() *PromoCodeUpdate {
	_u.mutation.ClearValidUntil()
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *PromoCodeUpdate) SetMaxUses(v int) *PromoCodeUpdate {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableMaxUses(v *int) *PromoCodeUpdate {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *PromoCodeUpdate) AddMaxUses(v int) *PromoCodeUpdate {
	_u.mutation.AddMaxUses(v)
	return _u
}

// ClearMaxUses clears the value of the "max_uses" field.
func (_u *PromoCodeUpdate) ClearMaxUses() *PromoCodeUpdate {
	_u.mutation.ClearMaxUses()
	return _u
}

// SetUsesCount sets the "uses_count" field.
func (_u *PromoCodeUpdate) SetUsesCount(v int) *PromoCodeUpdate {
	_u.mutation.ResetUsesCount()
	_u.mutation.SetUsesCount(v)
	return _u
}

// SetNillableUsesCount sets the "uses_count" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableUsesCount(v *int) *PromoCodeUpdate {
	if v != nil {
		_u.SetUsesCount(*v)
	}
	return _u
}

// AddUsesCount adds value to the "uses_count" field.
func (_u *PromoCodeUpdate) AddUsesCount(v int) *PromoCodeUpdate {
	_u.mutation.AddUsesCount(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromoCodeUpdate) SetEnabled(v bool) *PromoCodeUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromoCodeUpdate) SetNillableEnabled(v *bool) *PromoCodeUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddUsageIDs adds the "usages" edge to the PromoCodeUsage entity by IDs.
func (_u *PromoCodeUpdate) AddUsageIDs(ids ...string) *PromoCodeUpdate {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the PromoCodeUsage entity.
func (_u *PromoCodeUpdate) AddUsages(v ...*PromoCodeUsage) *PromoCodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the PromoCodeMutation object of the builder.
func (_u *PromoCodeUpdate) Mutation() *PromoCodeMutation {
	return _u.mutation
}

// ClearUsages clears all "usages" edges to the PromoCodeUsage entity.
func (_u *PromoCodeUpdate) ClearUsages() *PromoCodeUpdate {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to PromoCodeUsage entities by IDs.
func (_u *PromoCodeUpdate) RemoveUsageIDs(ids ...string) *PromoCodeUpdate {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to PromoCodeUsage entities.
func (_u *PromoCodeUpdate) RemoveUsages(v ...*PromoCodeUsage) *PromoCodeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromoCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromoCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := promocode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "PromoCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountType(); ok {
		if err := promocode.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "PromoCode.discount_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountValue(); ok {
		if err := promocode.DiscountValueValidator(v); err != nil {
			return &ValidationError{Name: "discount_value", err: fmt.Errorf(`ent: validator failed for field "PromoCode.discount_value": %w`, err)}
		}
	}
	return nil
}

func (_u *PromoCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promocode.Table, promocode.Columns, sqlgraph.NewFieldSpec(promocode.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(promocode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountType(); ok {
		_spec.SetField(promocode.FieldDiscountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(promocode.FieldDiscountValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(promocode.FieldDiscountValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppliesTo(); ok {
		_spec.SetField(promocode.FieldAppliesTo, field.TypeString, value)
	}
	if _u.mutation.AppliesToCleared() {
		_spec.ClearField(promocode.FieldAppliesTo, field.TypeString)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(promocode.FieldValidFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(promocode.FieldValidUntil, field.TypeTime, value)
	}
	if _u.mutation.ValidUntilCleared() {
		_spec.ClearField(promocode.FieldValidUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(promocode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(promocode.FieldMaxUses, field.TypeInt, value)
	}
	if _u.mutation.MaxUsesCleared() {
		_spec.ClearField(promocode.FieldMaxUses, field.TypeInt)
	}
	if value, ok := _u.mutation.UsesCount(); ok {
		_spec.SetField(promocode.FieldUsesCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsesCount(); ok {
		_spec.AddField(promocode.FieldUsesCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promocode.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promocode.UsagesTable,
			Columns: []string{promocode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promocode.UsagesTable,
			Columns: []string{promocode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promocode.UsagesTable,
			Columns: []string{promocode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promocode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromoCodeUpdateOne is the builder for updating a single PromoCode entity.
type PromoCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromoCodeMutation
}

// SetCode sets the "code" field.
func (_u *PromoCodeUpdateOne) SetCode(v string) *PromoCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableCode(v *string) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDiscountType sets the "discount_type" field.
func (_u *PromoCodeUpdateOne) SetDiscountType(v promocode.DiscountType) *PromoCodeUpdateOne {
	_u.mutation.SetDiscountType(v)
	return _u
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableDiscountType(v *promocode.DiscountType) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetDiscountType(*v)
	}
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *PromoCodeUpdateOne) SetDiscountValue(v int) *PromoCodeUpdateOne {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableDiscountValue(v *int) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *PromoCodeUpdateOne) AddDiscountValue(v int) *PromoCodeUpdateOne {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// SetAppliesTo sets the "applies_to" field.
func (_u *PromoCodeUpdateOne) SetAppliesTo(v string) *PromoCodeUpdateOne {
	_u.mutation.SetAppliesTo(v)
	return _u
}

// SetNillableAppliesTo sets the "applies_to" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableAppliesTo(v *string) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetAppliesTo(*v)
	}
	return _u
}

// ClearAppliesTo clears the value of the "applies_to" field.
func (_u *PromoCodeUpdateOne) ClearAppliesTo() *PromoCodeUpdateOne {
	_u.mutation.ClearAppliesTo()
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *PromoCodeUpdateOne) SetValidFrom(v time.Time) *PromoCodeUpdateOne {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableValidFrom(v *time.Time) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// SetValidUntil sets the "valid_until" field.
func (_u *PromoCodeUpdateOne) SetValidUntil(v time.Time) *PromoCodeUpdateOne {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableValidUntil(v *time.Time) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// ClearValidUntil clears the value of the "valid_until" field.
func (_u *PromoCodeUpdateOne) ClearValidUntil() *PromoCodeUpdateOne {
	_u.mutation.ClearValidUntil()
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *PromoCodeUpdateOne) SetMaxUses(v int) *PromoCodeUpdateOne {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableMaxUses(v *int) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *PromoCodeUpdateOne) AddMaxUses(v int) *PromoCodeUpdateOne {
	_u.mutation.AddMaxUses(v)
	return _u
}

// ClearMaxUses clears the value of the "max_uses" field.
func (_u *PromoCodeUpdateOne) ClearMaxUses() *PromoCodeUpdateOne {
	_u.mutation.ClearMaxUses()
	return _u
}

// SetUsesCount sets the "uses_count" field.
func (_u *PromoCodeUpdateOne) SetUsesCount(v int) *PromoCodeUpdateOne {
	_u.mutation.ResetUsesCount()
	_u.mutation.SetUsesCount(v)
	return _u
}

// SetNillableUsesCount sets the "uses_count" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableUsesCount(v *int) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetUsesCount(*v)
	}
	return _u
}

// AddUsesCount adds value to the "uses_count" field.
func (_u *PromoCodeUpdateOne) AddUsesCount(v int) *PromoCodeUpdateOne {
	_u.mutation.AddUsesCount(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromoCodeUpdateOne) SetEnabled(v bool) *PromoCodeUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromoCodeUpdateOne) SetNillableEnabled(v *bool) *PromoCodeUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddUsageIDs adds the "usages" edge to the PromoCodeUsage entity by IDs.
func (_u *PromoCodeUpdateOne) AddUsageIDs(ids ...string) *PromoCodeUpdateOne {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the PromoCodeUsage entity.
func (_u *PromoCodeUpdateOne) AddUsages(v ...*PromoCodeUsage) *PromoCodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the PromoCodeMutation object of the builder.
func (_u *PromoCodeUpdateOne) Mutation() *PromoCodeMutation {
	return _u.mutation
}

// ClearUsages clears all "usages" edges to the PromoCodeUsage entity.
func (_u *PromoCodeUpdateOne) ClearUsages() *PromoCodeUpdateOne {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to PromoCodeUsage entities by IDs.
func (_u *PromoCodeUpdateOne) RemoveUsageIDs(ids ...string) *PromoCodeUpdateOne {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to PromoCodeUsage entities.
func (_u *PromoCodeUpdateOne) RemoveUsages(v ...*PromoCodeUsage) *PromoCodeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Where appends a list predicates to the PromoCodeUpdate builder.
func (_u *PromoCodeUpdateOne) Where(ps ...predicate.PromoCode) *PromoCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromoCodeUpdateOne) Select(field string, fields ...string) *PromoCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromoCode entity.
func (_u *PromoCodeUpdateOne) Save(ctx context.Context) (*PromoCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoCodeUpdateOne) SaveX(ctx context.Context) *PromoCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromoCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := promocode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "PromoCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountType(); ok {
		if err := promocode.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "PromoCode.discount_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountValue(); ok {
		if err := promocode.DiscountValueValidator(v); err != nil {
			return &ValidationError{Name: "discount_value", err: fmt.Errorf(`ent: validator failed for field "PromoCode.discount_value": %w`, err)}
		}
	}
	return nil
}

func (_u *PromoCodeUpdateOne) sqlSave(ctx context.Context) (_node *PromoCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promocode.Table, promocode.Columns, sqlgraph.NewFieldSpec(promocode.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromoCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promocode.FieldID)
		for _, f := range fields {
			if !promocode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promocode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(promocode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountType(); ok {
		_spec.SetField(promocode.FieldDiscountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(promocode.FieldDiscountValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(promocode.FieldDiscountValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AppliesTo(); ok {
		_spec.SetField(promocode.FieldAppliesTo, field.TypeString, value)
	}
	if _u.mutation.AppliesToCleared() {
		_spec.ClearField(promocode.FieldAppliesTo, field.TypeString)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(promocode.FieldValidFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(promocode.FieldValidUntil, field.TypeTime, value)
	}
	if _u.mutation.ValidUntilCleared() {
		_spec.ClearField(promocode.FieldValidUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(promocode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(promocode.FieldMaxUses, field.TypeInt, value)
	}
	if _u.mutation.MaxUsesCleared() {
		_spec.ClearField(promocode.FieldMaxUses, field.TypeInt)
	}
	if value, ok := _u.mutation.UsesCount(); ok {
		_spec.SetField(promocode.FieldUsesCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsesCount(); ok {
		_spec.AddField(promocode.FieldUsesCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promocode.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promocode.UsagesTable,
			Columns: []string{promocode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promocode.UsagesTable,
			Columns: []string{promocode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   promocode.UsagesTable,
			Columns: []string{promocode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PromoCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promocode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
