// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"srv.exe.dev/ent/promocode"
)

// PromoCode is the model entity for the PromoCode schema.
type PromoCode struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// DiscountType holds the value of the "discount_type" field.
	DiscountType promocode.DiscountType `json:"discount_type,omitempty"`
	// DiscountValue holds the value of the "discount_value" field.
	DiscountValue int `json:"discount_value,omitempty"`
	// AppliesTo holds the value of the "applies_to" field.
	AppliesTo *string `json:"applies_to,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidUntil holds the value of the "valid_until" field.
	ValidUntil *time.Time `json:"valid_until,omitempty"`
	// MaxUses holds the value of the "max_uses" field.
	MaxUses *int `json:"max_uses,omitempty"`
	// UsesCount holds the value of the "uses_count" field.
	UsesCount int `json:"uses_count,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PromoCodeQuery when eager-loading is set.
	Edges        PromoCodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PromoCodeEdges holds the relations/edges for other nodes in the graph.
type PromoCodeEdges struct {
	// Usages holds the value of the usages edge.
	Usages []*PromoCodeUsage `json:"usages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsagesOrErr returns the Usages value or an error if the edge
// was not loaded in eager-loading.
func (e PromoCodeEdges) UsagesOrErr() ([]*PromoCodeUsage, error) {
	if e.loadedTypes[0] {
		return e.Usages, nil
	}
	return nil, &NotLoadedError{edge: "usages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromoCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promocode.FieldEnabled:
			values[i] = new(sql.NullBool)
		case promocode.FieldDiscountValue, promocode.FieldMaxUses, promocode.FieldUsesCount:
			values[i] = new(sql.NullInt64)
		case promocode.FieldID, promocode.FieldCode, promocode.FieldDiscountType, promocode.FieldAppliesTo:
			values[i] = new(sql.NullString)
		case promocode.FieldValidFrom, promocode.FieldValidUntil, promocode.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromoCode fields.
func (_m *PromoCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promocode.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case promocode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case promocode.FieldDiscountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discount_type", values[i])
			} else if value.Valid {
				_m.DiscountType = promocode.DiscountType(value.String)
			}
		case promocode.FieldDiscountValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_value", values[i])
			} else if value.Valid {
				_m.DiscountValue = int(value.Int64)
			}
		case promocode.FieldAppliesTo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field applies_to", values[i])
			} else if value.Valid {
				_m.AppliesTo = new(string)
				*_m.AppliesTo = value.String
			}
		case promocode.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case promocode.FieldValidUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_until", values[i])
			} else if value.Valid {
				_m.ValidUntil = new(time.Time)
				*_m.ValidUntil = value.Time
			}
		case promocode.FieldMaxUses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses", values[i])
			} else if value.Valid {
				_m.MaxUses = new(int)
				*_m.MaxUses = int(value.Int64)
			}
		case promocode.FieldUsesCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uses_count", values[i])
			} else if value.Valid {
				_m.UsesCount = int(value.Int64)
			}
		case promocode.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case promocode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromoCode.
// This includes values selected through modifiers, order, etc.
func (_m *PromoCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsages queries the "usages" edge of the PromoCode entity.
func (_m *PromoCode) QueryUsages() *PromoCodeUsageQuery {
	return NewPromoCodeClient(_m.config).QueryUsages(_m)
}

// Update returns a builder for updating this PromoCode.
// Note that you need to call PromoCode.Unwrap() before calling this method if this PromoCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromoCode) Update() *PromoCodeUpdateOne {
	return NewPromoCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromoCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromoCode) Unwrap() *PromoCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromoCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromoCode) String() string {
	var builder strings.Builder
	builder.WriteString("PromoCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("discount_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountType))
	builder.WriteString(", ")
	builder.WriteString("discount_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountValue))
	builder.WriteString(", ")
	if v := _m.AppliesTo; v != nil {
		builder.WriteString("applies_to=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidUntil; v != nil {
		builder.WriteString("valid_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.MaxUses; v != nil {
		builder.WriteString("max_uses=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("uses_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsesCount))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PromoCodes is a parsable slice of PromoCode.
type PromoCodes []*PromoCode
