// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/municipality"
	"srv.exe.dev/ent/predicate"
	"srv.exe.dev/ent/scrapejob"
)

// ScrapeJobUpdate is the builder for updating ScrapeJob entities.
type ScrapeJobUpdate struct {
	config
	hooks    []Hook
	mutation *ScrapeJobMutation
}

// Where appends a list predicates to the ScrapeJobUpdate builder.
func (_u *ScrapeJobUpdate) Where(ps ...predicate.ScrapeJob) *ScrapeJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMunicipalityID sets the "municipality_id" field.
func (_u *ScrapeJobUpdate) SetMunicipalityID(v string) *ScrapeJobUpdate {
	_u.mutation.SetMunicipalityID(v)
	return _u
}

// SetNillableMunicipalityID sets the "municipality_id" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableMunicipalityID(v *string) *ScrapeJobUpdate {
	if v != nil {
		_u.SetMunicipalityID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScrapeJobUpdate) SetStatus(v scrapejob.Status) *ScrapeJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableStatus(v *scrapejob.Status) *ScrapeJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSlotsFound sets the "slots_found" field.
func (_u *ScrapeJobUpdate) SetSlotsFound(v int) *ScrapeJobUpdate {
	_u.mutation.ResetSlotsFound()
	_u.mutation.SetSlotsFound(v)
	return _u
}

// SetNillableSlotsFound sets the "slots_found" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableSlotsFound(v *int) *ScrapeJobUpdate {
	if v != nil {
		_u.SetSlotsFound(*v)
	}
	return _u
}

// AddSlotsFound adds value to the "slots_found" field.
func (_u *ScrapeJobUpdate) AddSlotsFound(v int) *ScrapeJobUpdate {
	_u.mutation.AddSlotsFound(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScrapeJobUpdate) SetErrorMessage(v string) *ScrapeJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableErrorMessage(v *string) *ScrapeJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ScrapeJobUpdate) ClearErrorMessage() *ScrapeJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetScrapeStatus sets the "scrape_status" field.
func (_u *ScrapeJobUpdate) SetScrapeStatus(v string) *ScrapeJobUpdate {
	_u.mutation.SetScrapeStatus(v)
	return _u
}

// SetNillableScrapeStatus sets the "scrape_status" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableScrapeStatus(v *string) *ScrapeJobUpdate {
	if v != nil {
		_u.SetScrapeStatus(*v)
	}
	return _u
}

// ClearScrapeStatus clears the value of the "scrape_status" field.
func (_u *ScrapeJobUpdate) ClearScrapeStatus() *ScrapeJobUpdate {
	_u.mutation.ClearScrapeStatus()
	return _u
}

// SetDiagnostics sets the "diagnostics" field.
func (_u *ScrapeJobUpdate) SetDiagnostics(v string) *ScrapeJobUpdate {
	_u.mutation.SetDiagnostics(v)
	return _u
}

// SetNillableDiagnostics sets the "diagnostics" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableDiagnostics(v *string) *ScrapeJobUpdate {
	if v != nil {
		_u.SetDiagnostics(*v)
	}
	return _u
}

// ClearDiagnostics clears the value of the "diagnostics" field.
func (_u *ScrapeJobUpdate) ClearDiagnostics() *ScrapeJobUpdate {
	_u.mutation.ClearDiagnostics()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ScrapeJobUpdate) SetStartedAt(v time.Time) *ScrapeJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableStartedAt(v *time.Time) *ScrapeJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ScrapeJobUpdate) ClearStartedAt() *ScrapeJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ScrapeJobUpdate) SetCompletedAt(v time.Time) *ScrapeJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ScrapeJobUpdate) SetNillableCompletedAt(v *time.Time) *ScrapeJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ScrapeJobUpdate) ClearCompletedAt() *ScrapeJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetMunicipality sets the "municipality" edge to the Municipality entity.
func (_u *ScrapeJobUpdate) SetMunicipality(v *Municipality) *ScrapeJobUpdate {
	return _u.SetMunicipalityID(v.ID)
}

// Mutation returns the ScrapeJobMutation object of the builder.
func (_u *ScrapeJobUpdate) Mutation() *ScrapeJobMutation {
	return _u.mutation
}

// ClearMunicipality clears the "municipality" edge to the Municipality entity.
func (_u *ScrapeJobUpdate) ClearMunicipality() *ScrapeJobUpdate {
	_u.mutation.ClearMunicipality()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScrapeJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScrapeJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScrapeJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScrapeJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScrapeJobUpdate) check() error {
	if v, ok := _u.mutation.MunicipalityID(); ok {
		if err := scrapejob.MunicipalityIDValidator(v); err != nil {
			return &ValidationError{Name: "municipality_id", err: fmt.Errorf(`ent: validator failed for field "ScrapeJob.municipality_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := scrapejob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScrapeJob.status": %w`, err)}
		}
	}
	if _u.mutation.MunicipalityCleared() && len(_u.mutation.MunicipalityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScrapeJob.municipality"`)
	}
	return nil
}

func (_u *ScrapeJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scrapejob.Table, scrapejob.Columns, sqlgraph.NewFieldSpec(scrapejob.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scrapejob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SlotsFound(); ok {
		_spec.SetField(scrapejob.FieldSlotsFound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlotsFound(); ok {
		_spec.AddField(scrapejob.FieldSlotsFound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(scrapejob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(scrapejob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapeStatus(); ok {
		_spec.SetField(scrapejob.FieldScrapeStatus, field.TypeString, value)
	}
	if _u.mutation.ScrapeStatusCleared() {
		_spec.ClearField(scrapejob.FieldScrapeStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Diagnostics(); ok {
		_spec.SetField(scrapejob.FieldDiagnostics, field.TypeString, value)
	}
	if _u.mutation.DiagnosticsCleared() {
		_spec.ClearField(scrapejob.FieldDiagnostics, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(scrapejob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(scrapejob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(scrapejob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(scrapejob.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.MunicipalityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scrapejob.MunicipalityTable,
			Columns: []string{scrapejob.MunicipalityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(municipality.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MunicipalityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scrapejob.MunicipalityTable,
			Columns: []string{scrapejob.MunicipalityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(municipality.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scrapejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScrapeJobUpdateOne is the builder for updating a single ScrapeJob entity.
type ScrapeJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScrapeJobMutation
}

// SetMunicipalityID sets the "municipality_id" field.
func (_u *ScrapeJobUpdateOne) SetMunicipalityID(v string) *ScrapeJobUpdateOne {
	_u.mutation.SetMunicipalityID(v)
	return _u
}

// SetNillableMunicipalityID sets the "municipality_id" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableMunicipalityID(v *string) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetMunicipalityID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScrapeJobUpdateOne) SetStatus(v scrapejob.Status) *ScrapeJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableStatus(v *scrapejob.Status) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSlotsFound sets the "slots_found" field.
func (_u *ScrapeJobUpdateOne) SetSlotsFound(v int) *ScrapeJobUpdateOne {
	_u.mutation.ResetSlotsFound()
	_u.mutation.SetSlotsFound(v)
	return _u
}

// SetNillableSlotsFound sets the "slots_found" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableSlotsFound(v *int) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetSlotsFound(*v)
	}
	return _u
}

// AddSlotsFound adds value to the "slots_found" field.
func (_u *ScrapeJobUpdateOne) AddSlotsFound(v int) *ScrapeJobUpdateOne {
	_u.mutation.AddSlotsFound(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScrapeJobUpdateOne) SetErrorMessage(v string) *ScrapeJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableErrorMessage(v *string) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ScrapeJobUpdateOne) ClearErrorMessage() *ScrapeJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetScrapeStatus sets the "scrape_status" field.
func (_u *ScrapeJobUpdateOne) SetScrapeStatus(v string) *ScrapeJobUpdateOne {
	_u.mutation.SetScrapeStatus(v)
	return _u
}

// SetNillableScrapeStatus sets the "scrape_status" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableScrapeStatus(v *string) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetScrapeStatus(*v)
	}
	return _u
}

// ClearScrapeStatus clears the value of the "scrape_status" field.
func (_u *ScrapeJobUpdateOne) ClearScrapeStatus() *ScrapeJobUpdateOne {
	_u.mutation.ClearScrapeStatus()
	return _u
}

// SetDiagnostics sets the "diagnostics" field.
func (_u *ScrapeJobUpdateOne) SetDiagnostics(v string) *ScrapeJobUpdateOne {
	_u.mutation.SetDiagnostics(v)
	return _u
}

// SetNillableDiagnostics sets the "diagnostics" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableDiagnostics(v *string) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetDiagnostics(*v)
	}
	return _u
}

// ClearDiagnostics clears the value of the "diagnostics" field.
func (_u *ScrapeJobUpdateOne) ClearDiagnostics() *ScrapeJobUpdateOne {
	_u.mutation.ClearDiagnostics()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ScrapeJobUpdateOne) SetStartedAt(v time.Time) *ScrapeJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableStartedAt(v *time.Time) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ScrapeJobUpdateOne) ClearStartedAt() *ScrapeJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ScrapeJobUpdateOne) SetCompletedAt(v time.Time) *ScrapeJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ScrapeJobUpdateOne) SetNillableCompletedAt(v *time.Time) *ScrapeJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ScrapeJobUpdateOne) ClearCompletedAt() *ScrapeJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetMunicipality sets the "municipality" edge to the Municipality entity.
func (_u *ScrapeJobUpdateOne) SetMunicipality(v *Municipality) *ScrapeJobUpdateOne {
	return _u.SetMunicipalityID(v.ID)
}

// Mutation returns the ScrapeJobMutation object of the builder.
func (_u *ScrapeJobUpdateOne) Mutation() *ScrapeJobMutation {
	return _u.mutation
}

// ClearMunicipality clears the "municipality" edge to the Municipality entity.
func (_u *ScrapeJobUpdateOne) ClearMunicipality() *ScrapeJobUpdateOne {
	_u.mutation.ClearMunicipality()
	return _u
}

// Where appends a list predicates to the ScrapeJobUpdate builder.
func (_u *ScrapeJobUpdateOne) Where(ps ...predicate.ScrapeJob) *ScrapeJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScrapeJobUpdateOne) Select(field string, fields ...string) *ScrapeJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScrapeJob entity.
func (_u *ScrapeJobUpdateOne) Save(ctx context.Context) (*ScrapeJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScrapeJobUpdateOne) SaveX(ctx context.Context) *ScrapeJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScrapeJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScrapeJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScrapeJobUpdateOne) check() error {
	if v, ok := _u.mutation.MunicipalityID(); ok {
		if err := scrapejob.MunicipalityIDValidator(v); err != nil {
			return &ValidationError{Name: "municipality_id", err: fmt.Errorf(`ent: validator failed for field "ScrapeJob.municipality_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := scrapejob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ScrapeJob.status": %w`, err)}
		}
	}
	if _u.mutation.MunicipalityCleared() && len(_u.mutation.MunicipalityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScrapeJob.municipality"`)
	}
	return nil
}

func (_u *ScrapeJobUpdateOne) sqlSave(ctx context.Context) (_node *ScrapeJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scrapejob.Table, scrapejob.Columns, sqlgraph.NewFieldSpec(scrapejob.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScrapeJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scrapejob.FieldID)
		for _, f := range fields {
			if !scrapejob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scrapejob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scrapejob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SlotsFound(); ok {
		_spec.SetField(scrapejob.FieldSlotsFound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSlotsFound(); ok {
		_spec.AddField(scrapejob.FieldSlotsFound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(scrapejob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(scrapejob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapeStatus(); ok {
		_spec.SetField(scrapejob.FieldScrapeStatus, field.TypeString, value)
	}
	if _u.mutation.ScrapeStatusCleared() {
		_spec.ClearField(scrapejob.FieldScrapeStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Diagnostics(); ok {
		_spec.SetField(scrapejob.FieldDiagnostics, field.TypeString, value)
	}
	if _u.mutation.DiagnosticsCleared() {
		_spec.ClearField(scrapejob.FieldDiagnostics, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(scrapejob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(scrapejob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(scrapejob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(scrapejob.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.MunicipalityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scrapejob.MunicipalityTable,
			Columns: []string{scrapejob.MunicipalityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(municipality.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MunicipalityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scrapejob.MunicipalityTable,
			Columns: []string{scrapejob.MunicipalityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(municipality.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScrapeJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scrapejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
