// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/predicate"
	"srv.exe.dev/ent/supportmessage"
	"srv.exe.dev/ent/supportticket"
	"srv.exe.dev/ent/team"
)

// SupportTicketUpdate is the builder for updating SupportTicket entities.
type SupportTicketUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdate) Where(ps ...predicate.SupportTicket) *SupportTicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *SupportTicketUpdate) SetTeamID(v string) *SupportTicketUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableTeamID(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *SupportTicketUpdate) ClearTeamID() *SupportTicketUpdate {
	_u.mutation.ClearTeamID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *SupportTicketUpdate) SetEmail(v string) *SupportTicketUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableEmail(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportTicketUpdate) SetSubject(v string) *SupportTicketUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableSubject(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdate) SetStatus(v supportticket.Status) *SupportTicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableStatus(v *supportticket.Status) *SupportTicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportTicketUpdate) SetPriority(v supportticket.Priority) *SupportTicketUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillablePriority(v *supportticket.Priority) *SupportTicketUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAiResponse sets the "ai_response" field.
func (_u *SupportTicketUpdate) SetAiResponse(v string) *SupportTicketUpdate {
	_u.mutation.SetAiResponse(v)
	return _u
}

// SetNillableAiResponse sets the "ai_response" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableAiResponse(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetAiResponse(*v)
	}
	return _u
}

// ClearAiResponse clears the value of the "ai_response" field.
func (_u *SupportTicketUpdate) ClearAiResponse() *SupportTicketUpdate {
	_u.mutation.ClearAiResponse()
	return _u
}

// SetHumanResponse sets the "human_response" field.
func (_u *SupportTicketUpdate) SetHumanResponse(v string) *SupportTicketUpdate {
	_u.mutation.SetHumanResponse(v)
	return _u
}

// SetNillableHumanResponse sets the "human_response" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableHumanResponse(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetHumanResponse(*v)
	}
	return _u
}

// ClearHumanResponse clears the value of the "human_response" field.
func (_u *SupportTicketUpdate) ClearHumanResponse() *SupportTicketUpdate {
	_u.mutation.ClearHumanResponse()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdate) SetUpdatedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *SupportTicketUpdate) SetTeam(v *Team) *SupportTicketUpdate {
	return _u.SetTeamID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportMessage entity by IDs.
func (_u *SupportTicketUpdate) AddMessageIDs(ids ...string) *SupportTicketUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportMessage entity.
func (_u *SupportTicketUpdate) AddMessages(v ...*SupportMessage) *SupportTicketUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdate) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *SupportTicketUpdate) ClearTeam() *SupportTicketUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportMessage entity.
func (_u *SupportTicketUpdate) ClearMessages() *SupportTicketUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportMessage entities by IDs.
func (_u *SupportTicketUpdate) RemoveMessageIDs(ids ...string) *SupportTicketUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportMessage entities.
func (_u *SupportTicketUpdate) RemoveMessages(v ...*SupportMessage) *SupportTicketUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := supportticket.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.priority": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(supportticket.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportticket.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AiResponse(); ok {
		_spec.SetField(supportticket.FieldAiResponse, field.TypeString, value)
	}
	if _u.mutation.AiResponseCleared() {
		_spec.ClearField(supportticket.FieldAiResponse, field.TypeString)
	}
	if value, ok := _u.mutation.HumanResponse(); ok {
		_spec.SetField(supportticket.FieldHumanResponse, field.TypeString, value)
	}
	if _u.mutation.HumanResponseCleared() {
		_spec.ClearField(supportticket.FieldHumanResponse, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.TeamTable,
			Columns: []string{supportticket.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.TeamTable,
			Columns: []string{supportticket.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketUpdateOne is the builder for updating a single SupportTicket entity.
type SupportTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMutation
}

// SetTeamID sets the "team_id" field.
func (_u *SupportTicketUpdateOne) SetTeamID(v string) *SupportTicketUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableTeamID(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *SupportTicketUpdateOne) ClearTeamID() *SupportTicketUpdateOne {
	_u.mutation.ClearTeamID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *SupportTicketUpdateOne) SetEmail(v string) *SupportTicketUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableEmail(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportTicketUpdateOne) SetSubject(v string) *SupportTicketUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableSubject(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdateOne) SetStatus(v supportticket.Status) *SupportTicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableStatus(v *supportticket.Status) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportTicketUpdateOne) SetPriority(v supportticket.Priority) *SupportTicketUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillablePriority(v *supportticket.Priority) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAiResponse sets the "ai_response" field.
func (_u *SupportTicketUpdateOne) SetAiResponse(v string) *SupportTicketUpdateOne {
	_u.mutation.SetAiResponse(v)
	return _u
}

// SetNillableAiResponse sets the "ai_response" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableAiResponse(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetAiResponse(*v)
	}
	return _u
}

// ClearAiResponse clears the value of the "ai_response" field.
func (_u *SupportTicketUpdateOne) ClearAiResponse() *SupportTicketUpdateOne {
	_u.mutation.ClearAiResponse()
	return _u
}

// SetHumanResponse sets the "human_response" field.
func (_u *SupportTicketUpdateOne) SetHumanResponse(v string) *SupportTicketUpdateOne {
	_u.mutation.SetHumanResponse(v)
	return _u
}

// SetNillableHumanResponse sets the "human_response" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableHumanResponse(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetHumanResponse(*v)
	}
	return _u
}

// ClearHumanResponse clears the value of the "human_response" field.
func (_u *SupportTicketUpdateOne) ClearHumanResponse() *SupportTicketUpdateOne {
	_u.mutation.ClearHumanResponse()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *SupportTicketUpdateOne) SetTeam(v *Team) *SupportTicketUpdateOne {
	return _u.SetTeamID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportMessage entity by IDs.
func (_u *SupportTicketUpdateOne) AddMessageIDs(ids ...string) *SupportTicketUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportMessage entity.
func (_u *SupportTicketUpdateOne) AddMessages(v ...*SupportMessage) *SupportTicketUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdateOne) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *SupportTicketUpdateOne) ClearTeam() *SupportTicketUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportMessage entity.
func (_u *SupportTicketUpdateOne) ClearMessages() *SupportTicketUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportMessage entities by IDs.
func (_u *SupportTicketUpdateOne) RemoveMessageIDs(ids ...string) *SupportTicketUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportMessage entities.
func (_u *SupportTicketUpdateOne) RemoveMessages(v ...*SupportMessage) *SupportTicketUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdateOne) Where(ps ...predicate.SupportTicket) *SupportTicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketUpdateOne) Select(field string, fields ...string) *SupportTicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicket entity.
func (_u *SupportTicketUpdateOne) Save(ctx context.Context) (*SupportTicket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) SaveX(ctx context.Context) *SupportTicket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := supportticket.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.priority": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticket.FieldID)
		for _, f := range fields {
			if !supportticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(supportticket.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportticket.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AiResponse(); ok {
		_spec.SetField(supportticket.FieldAiResponse, field.TypeString, value)
	}
	if _u.mutation.AiResponseCleared() {
		_spec.ClearField(supportticket.FieldAiResponse, field.TypeString)
	}
	if value, ok := _u.mutation.HumanResponse(); ok {
		_spec.SetField(supportticket.FieldHumanResponse, field.TypeString, value)
	}
	if _u.mutation.HumanResponseCleared() {
		_spec.ClearField(supportticket.FieldHumanResponse, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.TeamTable,
			Columns: []string{supportticket.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.TeamTable,
			Columns: []string{supportticket.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
