// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/predicate"
	"srv.exe.dev/ent/supportmessage"
	"srv.exe.dev/ent/supportticket"
)

// SupportMessageUpdate is the builder for updating SupportMessage entities.
type SupportMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SupportMessageMutation
}

// Where appends a list predicates to the SupportMessageUpdate builder.
func (_u *SupportMessageUpdate) Where(ps ...predicate.SupportMessage) *SupportMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportMessageUpdate) SetTicketID(v string) *SupportMessageUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableTicketID(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *SupportMessageUpdate) SetRole(v supportmessage.Role) *SupportMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableRole(v *supportmessage.Role) *SupportMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportMessageUpdate) SetContent(v string) *SupportMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportMessageUpdate) SetNillableContent(v *string) *SupportMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportMessageUpdate) SetTicket(v *SupportTicket) *SupportMessageUpdate {
	return _u.SetTicketID(v.ID)
}

// Mutation returns the SupportMessageMutation object of the builder.
func (_u *SupportMessageUpdate) Mutation() *SupportMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportMessageUpdate) ClearTicket() *SupportMessageUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportMessageUpdate) check() error {
	if v, ok := _u.mutation.TicketID(); ok {
		if err := supportmessage.TicketIDValidator(v); err != nil {
			return &ValidationError{Name: "ticket_id", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.ticket_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := supportmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportMessage.ticket"`)
	}
	return nil
}

func (_u *SupportMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportmessage.Table, supportmessage.Columns, sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(supportmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.TicketTable,
			Columns: []string{supportmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.TicketTable,
			Columns: []string{supportmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportMessageUpdateOne is the builder for updating a single SupportMessage entity.
type SupportMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportMessageMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportMessageUpdateOne) SetTicketID(v string) *SupportMessageUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableTicketID(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *SupportMessageUpdateOne) SetRole(v supportmessage.Role) *SupportMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableRole(v *supportmessage.Role) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportMessageUpdateOne) SetContent(v string) *SupportMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportMessageUpdateOne) SetNillableContent(v *string) *SupportMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportMessageUpdateOne) SetTicket(v *SupportTicket) *SupportMessageUpdateOne {
	return _u.SetTicketID(v.ID)
}

// Mutation returns the SupportMessageMutation object of the builder.
func (_u *SupportMessageUpdateOne) Mutation() *SupportMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportMessageUpdateOne) ClearTicket() *SupportMessageUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// Where appends a list predicates to the SupportMessageUpdate builder.
func (_u *SupportMessageUpdateOne) Where(ps ...predicate.SupportMessage) *SupportMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportMessageUpdateOne) Select(field string, fields ...string) *SupportMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportMessage entity.
func (_u *SupportMessageUpdateOne) Save(ctx context.Context) (*SupportMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportMessageUpdateOne) SaveX(ctx context.Context) *SupportMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportMessageUpdateOne) check() error {
	if v, ok := _u.mutation.TicketID(); ok {
		if err := supportmessage.TicketIDValidator(v); err != nil {
			return &ValidationError{Name: "ticket_id", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.ticket_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := supportmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportMessage.content": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportMessage.ticket"`)
	}
	return nil
}

func (_u *SupportMessageUpdateOne) sqlSave(ctx context.Context) (_node *SupportMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportmessage.Table, supportmessage.Columns, sqlgraph.NewFieldSpec(supportmessage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportmessage.FieldID)
		for _, f := range fields {
			if !supportmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(supportmessage.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.TicketTable,
			Columns: []string{supportmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportmessage.TicketTable,
			Columns: []string{supportmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
