// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"srv.exe.dev/ent/facility"
	"srv.exe.dev/ent/notification"
	"srv.exe.dev/ent/predicate"
	"srv.exe.dev/ent/team"
	"srv.exe.dev/ent/watchcondition"
)

// WatchConditionQuery is the builder for querying WatchCondition entities.
type WatchConditionQuery struct {
	config
	ctx               *QueryContext
	order             []watchcondition.OrderOption
	inters            []Interceptor
	predicates        []predicate.WatchCondition
	withTeam          *TeamQuery
	withFacility      *FacilityQuery
	withNotifications *NotificationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WatchConditionQuery builder.
func (_q *WatchConditionQuery) Where(ps ...predicate.WatchCondition) *WatchConditionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WatchConditionQuery) Limit(limit int) *WatchConditionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WatchConditionQuery) Offset(offset int) *WatchConditionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WatchConditionQuery) Unique(unique bool) *WatchConditionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WatchConditionQuery) Order(o ...watchcondition.OrderOption) *WatchConditionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTeam chains the current query on the "team" edge.
func (_q *WatchConditionQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(watchcondition.Table, watchcondition.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, watchcondition.TeamTable, watchcondition.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFacility chains the current query on the "facility" edge.
func (_q *WatchConditionQuery) QueryFacility() *FacilityQuery {
	query := (&FacilityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(watchcondition.Table, watchcondition.FieldID, selector),
			sqlgraph.To(facility.Table, facility.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, watchcondition.FacilityTable, watchcondition.FacilityColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNotifications chains the current query on the "notifications" edge.
func (_q *WatchConditionQuery) QueryNotifications() *NotificationQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(watchcondition.Table, watchcondition.FieldID, selector),
			sqlgraph.To(notification.Table, notification.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, watchcondition.NotificationsTable, watchcondition.NotificationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WatchCondition entity from the query.
// Returns a *NotFoundError when no WatchCondition was found.
func (_q *WatchConditionQuery) First(ctx context.Context) (*WatchCondition, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{watchcondition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WatchConditionQuery) FirstX(ctx context.Context) *WatchCondition {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WatchCondition ID from the query.
// Returns a *NotFoundError when no WatchCondition ID was found.
func (_q *WatchConditionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{watchcondition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WatchConditionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WatchCondition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WatchCondition entity is found.
// Returns a *NotFoundError when no WatchCondition entities are found.
func (_q *WatchConditionQuery) Only(ctx context.Context) (*WatchCondition, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{watchcondition.Label}
	default:
		return nil, &NotSingularError{watchcondition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WatchConditionQuery) OnlyX(ctx context.Context) *WatchCondition {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WatchCondition ID in the query.
// Returns a *NotSingularError when more than one WatchCondition ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WatchConditionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{watchcondition.Label}
	default:
		err = &NotSingularError{watchcondition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WatchConditionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WatchConditions.
func (_q *WatchConditionQuery) All(ctx context.Context) ([]*WatchCondition, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WatchCondition, *WatchConditionQuery]()
	return withInterceptors[[]*WatchCondition](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WatchConditionQuery) AllX(ctx context.Context) []*WatchCondition {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WatchCondition IDs.
func (_q *WatchConditionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(watchcondition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WatchConditionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WatchConditionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WatchConditionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WatchConditionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WatchConditionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WatchConditionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WatchConditionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WatchConditionQuery) Clone() *WatchConditionQuery {
	if _q == nil {
		return nil
	}
	return &WatchConditionQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]watchcondition.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.WatchCondition{}, _q.predicates...),
		withTeam:          _q.withTeam.Clone(),
		withFacility:      _q.withFacility.Clone(),
		withNotifications: _q.withNotifications.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WatchConditionQuery) WithTeam(opts ...func(*TeamQuery)) *WatchConditionQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeam = query
	return _q
}

// WithFacility tells the query-builder to eager-load the nodes that are connected to
// the "facility" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WatchConditionQuery) WithFacility(opts ...func(*FacilityQuery)) *WatchConditionQuery {
	query := (&FacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFacility = query
	return _q
}

// WithNotifications tells the query-builder to eager-load the nodes that are connected to
// the "notifications" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WatchConditionQuery) WithNotifications(opts ...func(*NotificationQuery)) *WatchConditionQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNotifications = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TeamID string `json:"team_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WatchCondition.Query().
//		GroupBy(watchcondition.FieldTeamID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WatchConditionQuery) GroupBy(field string, fields ...string) *WatchConditionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WatchConditionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = watchcondition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TeamID string `json:"team_id,omitempty"`
//	}
//
//	client.WatchCondition.Query().
//		Select(watchcondition.FieldTeamID).
//		Scan(ctx, &v)
func (_q *WatchConditionQuery) Select(fields ...string) *WatchConditionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WatchConditionSelect{WatchConditionQuery: _q}
	sbuild.label = watchcondition.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WatchConditionSelect configured with the given aggregations.
func (_q *WatchConditionQuery) Aggregate(fns ...AggregateFunc) *WatchConditionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WatchConditionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !watchcondition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WatchConditionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WatchCondition, error) {
	var (
		nodes       = []*WatchCondition{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withTeam != nil,
			_q.withFacility != nil,
			_q.withNotifications != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WatchCondition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WatchCondition{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTeam; query != nil {
		if err := _q.loadTeam(ctx, query, nodes, nil,
			func(n *WatchCondition, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFacility; query != nil {
		if err := _q.loadFacility(ctx, query, nodes, nil,
			func(n *WatchCondition, e *Facility) { n.Edges.Facility = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNotifications; query != nil {
		if err := _q.loadNotifications(ctx, query, nodes,
			func(n *WatchCondition) { n.Edges.Notifications = []*Notification{} },
			func(n *WatchCondition, e *Notification) { n.Edges.Notifications = append(n.Edges.Notifications, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WatchConditionQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*WatchCondition, init func(*WatchCondition), assign func(*WatchCondition, *Team)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*WatchCondition)
	for i := range nodes {
		fk := nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WatchConditionQuery) loadFacility(ctx context.Context, query *FacilityQuery, nodes []*WatchCondition, init func(*WatchCondition), assign func(*WatchCondition, *Facility)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*WatchCondition)
	for i := range nodes {
		fk := nodes[i].FacilityID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(facility.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "facility_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WatchConditionQuery) loadNotifications(ctx context.Context, query *NotificationQuery, nodes []*WatchCondition, init func(*WatchCondition), assign func(*WatchCondition, *Notification)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*WatchCondition)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(notification.FieldWatchConditionID)
	}
	query.Where(predicate.Notification(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(watchcondition.NotificationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WatchConditionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "watch_condition_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *WatchConditionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WatchConditionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(watchcondition.Table, watchcondition.Columns, sqlgraph.NewFieldSpec(watchcondition.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, watchcondition.FieldID)
		for i := range fields {
			if fields[i] != watchcondition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTeam != nil {
			_spec.Node.AddColumnOnce(watchcondition.FieldTeamID)
		}
		if _q.withFacility != nil {
			_spec.Node.AddColumnOnce(watchcondition.FieldFacilityID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WatchConditionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(watchcondition.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = watchcondition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WatchConditionGroupBy is the group-by builder for WatchCondition entities.
type WatchConditionGroupBy struct {
	selector
	build *WatchConditionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WatchConditionGroupBy) Aggregate(fns ...AggregateFunc) *WatchConditionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WatchConditionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WatchConditionQuery, *WatchConditionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WatchConditionGroupBy) sqlScan(ctx context.Context, root *WatchConditionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WatchConditionSelect is the builder for selecting fields of WatchCondition entities.
type WatchConditionSelect struct {
	*WatchConditionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WatchConditionSelect) Aggregate(fns ...AggregateFunc) *WatchConditionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WatchConditionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WatchConditionQuery, *WatchConditionSelect](ctx, _s.WatchConditionQuery, _s, _s.inters, v)
}

func (_s *WatchConditionSelect) sqlScan(ctx context.Context, root *WatchConditionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
