// Code generated by ent, DO NOT EDIT.

package slot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the slot type in the database.
	Label = "slot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlotDate holds the string denoting the slot_date field in the database.
	FieldSlotDate = "slot_date"
	// FieldTimeFrom holds the string denoting the time_from field in the database.
	FieldTimeFrom = "time_from"
	// FieldTimeTo holds the string denoting the time_to field in the database.
	FieldTimeTo = "time_to"
	// FieldCourtName holds the string denoting the court_name field in the database.
	FieldCourtName = "court_name"
	// FieldRawText holds the string denoting the raw_text field in the database.
	FieldRawText = "raw_text"
	// FieldScrapedAt holds the string denoting the scraped_at field in the database.
	FieldScrapedAt = "scraped_at"
	// EdgeFacility holds the string denoting the facility edge name in mutations.
	EdgeFacility = "facility"
	// EdgeMunicipality holds the string denoting the municipality edge name in mutations.
	EdgeMunicipality = "municipality"
	// EdgeGround holds the string denoting the ground edge name in mutations.
	EdgeGround = "ground"
	// EdgeNotifications holds the string denoting the notifications edge name in mutations.
	EdgeNotifications = "notifications"
	// Table holds the table name of the slot in the database.
	Table = "slots"
	// FacilityTable is the table that holds the facility relation/edge.
	FacilityTable = "slots"
	// FacilityInverseTable is the table name for the Facility entity.
	// It exists in this package in order to avoid circular dependency with the "facility" package.
	FacilityInverseTable = "facilities"
	// FacilityColumn is the table column denoting the facility relation/edge.
	FacilityColumn = "facility_slots"
	// MunicipalityTable is the table that holds the municipality relation/edge.
	MunicipalityTable = "slots"
	// MunicipalityInverseTable is the table name for the Municipality entity.
	// It exists in this package in order to avoid circular dependency with the "municipality" package.
	MunicipalityInverseTable = "municipalities"
	// MunicipalityColumn is the table column denoting the municipality relation/edge.
	MunicipalityColumn = "municipality_slots"
	// GroundTable is the table that holds the ground relation/edge.
	GroundTable = "slots"
	// GroundInverseTable is the table name for the Ground entity.
	// It exists in this package in order to avoid circular dependency with the "ground" package.
	GroundInverseTable = "grounds"
	// GroundColumn is the table column denoting the ground relation/edge.
	GroundColumn = "ground_slots"
	// NotificationsTable is the table that holds the notifications relation/edge.
	NotificationsTable = "notifications"
	// NotificationsInverseTable is the table name for the Notification entity.
	// It exists in this package in order to avoid circular dependency with the "notification" package.
	NotificationsInverseTable = "notifications"
	// NotificationsColumn is the table column denoting the notifications relation/edge.
	NotificationsColumn = "slot_notifications"
)

// Columns holds all SQL columns for slot fields.
var Columns = []string{
	FieldID,
	FieldSlotDate,
	FieldTimeFrom,
	FieldTimeTo,
	FieldCourtName,
	FieldRawText,
	FieldScrapedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "slots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"facility_slots",
	"ground_slots",
	"municipality_slots",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TimeFromValidator is a validator for the "time_from" field. It is called by the builders before save.
	TimeFromValidator func(string) error
	// TimeToValidator is a validator for the "time_to" field. It is called by the builders before save.
	TimeToValidator func(string) error
	// DefaultScrapedAt holds the default value on creation for the "scraped_at" field.
	DefaultScrapedAt func() time.Time
)

// OrderOption defines the ordering options for the Slot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlotDate orders the results by the slot_date field.
func BySlotDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlotDate, opts...).ToFunc()
}

// ByTimeFrom orders the results by the time_from field.
func ByTimeFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeFrom, opts...).ToFunc()
}

// ByTimeTo orders the results by the time_to field.
func ByTimeTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeTo, opts...).ToFunc()
}

// ByCourtName orders the results by the court_name field.
func ByCourtName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCourtName, opts...).ToFunc()
}

// ByRawText orders the results by the raw_text field.
func ByRawText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawText, opts...).ToFunc()
}

// ByScrapedAt orders the results by the scraped_at field.
func ByScrapedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScrapedAt, opts...).ToFunc()
}

// ByFacilityField orders the results by facility field.
func ByFacilityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFacilityStep(), sql.OrderByField(field, opts...))
	}
}

// ByMunicipalityField orders the results by municipality field.
func ByMunicipalityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMunicipalityStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroundField orders the results by ground field.
func ByGroundField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroundStep(), sql.OrderByField(field, opts...))
	}
}

// ByNotificationsCount orders the results by notifications count.
func ByNotificationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationsStep(), opts...)
	}
}

// ByNotifications orders the results by notifications terms.
func ByNotifications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFacilityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FacilityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FacilityTable, FacilityColumn),
	)
}
func newMunicipalityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MunicipalityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MunicipalityTable, MunicipalityColumn),
	)
}
func newGroundStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroundInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroundTable, GroundColumn),
	)
}
func newNotificationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
	)
}
