// Code generated by ent, DO NOT EDIT.

package slot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"srv.exe.dev/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Slot {
	return predicate.Slot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Slot {
	return predicate.Slot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Slot {
	return predicate.Slot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Slot {
	return predicate.Slot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Slot {
	return predicate.Slot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Slot {
	return predicate.Slot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Slot {
	return predicate.Slot(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Slot {
	return predicate.Slot(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Slot {
	return predicate.Slot(sql.FieldContainsFold(FieldID, id))
}

// SlotDate applies equality check predicate on the "slot_date" field. It's identical to SlotDateEQ.
func SlotDate(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldSlotDate, v))
}

// TimeFrom applies equality check predicate on the "time_from" field. It's identical to TimeFromEQ.
func TimeFrom(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldTimeFrom, v))
}

// TimeTo applies equality check predicate on the "time_to" field. It's identical to TimeToEQ.
func TimeTo(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldTimeTo, v))
}

// CourtName applies equality check predicate on the "court_name" field. It's identical to CourtNameEQ.
func CourtName(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldCourtName, v))
}

// RawText applies equality check predicate on the "raw_text" field. It's identical to RawTextEQ.
func RawText(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldRawText, v))
}

// ScrapedAt applies equality check predicate on the "scraped_at" field. It's identical to ScrapedAtEQ.
func ScrapedAt(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldScrapedAt, v))
}

// SlotDateEQ applies the EQ predicate on the "slot_date" field.
func SlotDateEQ(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldSlotDate, v))
}

// SlotDateNEQ applies the NEQ predicate on the "slot_date" field.
func SlotDateNEQ(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldNEQ(FieldSlotDate, v))
}

// SlotDateIn applies the In predicate on the "slot_date" field.
func SlotDateIn(vs ...time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldIn(FieldSlotDate, vs...))
}

// SlotDateNotIn applies the NotIn predicate on the "slot_date" field.
func SlotDateNotIn(vs ...time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldNotIn(FieldSlotDate, vs...))
}

// SlotDateGT applies the GT predicate on the "slot_date" field.
func SlotDateGT(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldGT(FieldSlotDate, v))
}

// SlotDateGTE applies the GTE predicate on the "slot_date" field.
func SlotDateGTE(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldGTE(FieldSlotDate, v))
}

// SlotDateLT applies the LT predicate on the "slot_date" field.
func SlotDateLT(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldLT(FieldSlotDate, v))
}

// SlotDateLTE applies the LTE predicate on the "slot_date" field.
func SlotDateLTE(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldLTE(FieldSlotDate, v))
}

// TimeFromEQ applies the EQ predicate on the "time_from" field.
func TimeFromEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldTimeFrom, v))
}

// TimeFromNEQ applies the NEQ predicate on the "time_from" field.
func TimeFromNEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldNEQ(FieldTimeFrom, v))
}

// TimeFromIn applies the In predicate on the "time_from" field.
func TimeFromIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldIn(FieldTimeFrom, vs...))
}

// TimeFromNotIn applies the NotIn predicate on the "time_from" field.
func TimeFromNotIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldNotIn(FieldTimeFrom, vs...))
}

// TimeFromGT applies the GT predicate on the "time_from" field.
func TimeFromGT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGT(FieldTimeFrom, v))
}

// TimeFromGTE applies the GTE predicate on the "time_from" field.
func TimeFromGTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGTE(FieldTimeFrom, v))
}

// TimeFromLT applies the LT predicate on the "time_from" field.
func TimeFromLT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLT(FieldTimeFrom, v))
}

// TimeFromLTE applies the LTE predicate on the "time_from" field.
func TimeFromLTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLTE(FieldTimeFrom, v))
}

// TimeFromContains applies the Contains predicate on the "time_from" field.
func TimeFromContains(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContains(FieldTimeFrom, v))
}

// TimeFromHasPrefix applies the HasPrefix predicate on the "time_from" field.
func TimeFromHasPrefix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasPrefix(FieldTimeFrom, v))
}

// TimeFromHasSuffix applies the HasSuffix predicate on the "time_from" field.
func TimeFromHasSuffix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasSuffix(FieldTimeFrom, v))
}

// TimeFromEqualFold applies the EqualFold predicate on the "time_from" field.
func TimeFromEqualFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEqualFold(FieldTimeFrom, v))
}

// TimeFromContainsFold applies the ContainsFold predicate on the "time_from" field.
func TimeFromContainsFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContainsFold(FieldTimeFrom, v))
}

// TimeToEQ applies the EQ predicate on the "time_to" field.
func TimeToEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldTimeTo, v))
}

// TimeToNEQ applies the NEQ predicate on the "time_to" field.
func TimeToNEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldNEQ(FieldTimeTo, v))
}

// TimeToIn applies the In predicate on the "time_to" field.
func TimeToIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldIn(FieldTimeTo, vs...))
}

// TimeToNotIn applies the NotIn predicate on the "time_to" field.
func TimeToNotIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldNotIn(FieldTimeTo, vs...))
}

// TimeToGT applies the GT predicate on the "time_to" field.
func TimeToGT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGT(FieldTimeTo, v))
}

// TimeToGTE applies the GTE predicate on the "time_to" field.
func TimeToGTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGTE(FieldTimeTo, v))
}

// TimeToLT applies the LT predicate on the "time_to" field.
func TimeToLT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLT(FieldTimeTo, v))
}

// TimeToLTE applies the LTE predicate on the "time_to" field.
func TimeToLTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLTE(FieldTimeTo, v))
}

// TimeToContains applies the Contains predicate on the "time_to" field.
func TimeToContains(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContains(FieldTimeTo, v))
}

// TimeToHasPrefix applies the HasPrefix predicate on the "time_to" field.
func TimeToHasPrefix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasPrefix(FieldTimeTo, v))
}

// TimeToHasSuffix applies the HasSuffix predicate on the "time_to" field.
func TimeToHasSuffix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasSuffix(FieldTimeTo, v))
}

// TimeToEqualFold applies the EqualFold predicate on the "time_to" field.
func TimeToEqualFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEqualFold(FieldTimeTo, v))
}

// TimeToContainsFold applies the ContainsFold predicate on the "time_to" field.
func TimeToContainsFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContainsFold(FieldTimeTo, v))
}

// CourtNameEQ applies the EQ predicate on the "court_name" field.
func CourtNameEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldCourtName, v))
}

// CourtNameNEQ applies the NEQ predicate on the "court_name" field.
func CourtNameNEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldNEQ(FieldCourtName, v))
}

// CourtNameIn applies the In predicate on the "court_name" field.
func CourtNameIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldIn(FieldCourtName, vs...))
}

// CourtNameNotIn applies the NotIn predicate on the "court_name" field.
func CourtNameNotIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldNotIn(FieldCourtName, vs...))
}

// CourtNameGT applies the GT predicate on the "court_name" field.
func CourtNameGT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGT(FieldCourtName, v))
}

// CourtNameGTE applies the GTE predicate on the "court_name" field.
func CourtNameGTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGTE(FieldCourtName, v))
}

// CourtNameLT applies the LT predicate on the "court_name" field.
func CourtNameLT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLT(FieldCourtName, v))
}

// CourtNameLTE applies the LTE predicate on the "court_name" field.
func CourtNameLTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLTE(FieldCourtName, v))
}

// CourtNameContains applies the Contains predicate on the "court_name" field.
func CourtNameContains(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContains(FieldCourtName, v))
}

// CourtNameHasPrefix applies the HasPrefix predicate on the "court_name" field.
func CourtNameHasPrefix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasPrefix(FieldCourtName, v))
}

// CourtNameHasSuffix applies the HasSuffix predicate on the "court_name" field.
func CourtNameHasSuffix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasSuffix(FieldCourtName, v))
}

// CourtNameIsNil applies the IsNil predicate on the "court_name" field.
func CourtNameIsNil() predicate.Slot {
	return predicate.Slot(sql.FieldIsNull(FieldCourtName))
}

// CourtNameNotNil applies the NotNil predicate on the "court_name" field.
func CourtNameNotNil() predicate.Slot {
	return predicate.Slot(sql.FieldNotNull(FieldCourtName))
}

// CourtNameEqualFold applies the EqualFold predicate on the "court_name" field.
func CourtNameEqualFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEqualFold(FieldCourtName, v))
}

// CourtNameContainsFold applies the ContainsFold predicate on the "court_name" field.
func CourtNameContainsFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContainsFold(FieldCourtName, v))
}

// RawTextEQ applies the EQ predicate on the "raw_text" field.
func RawTextEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldRawText, v))
}

// RawTextNEQ applies the NEQ predicate on the "raw_text" field.
func RawTextNEQ(v string) predicate.Slot {
	return predicate.Slot(sql.FieldNEQ(FieldRawText, v))
}

// RawTextIn applies the In predicate on the "raw_text" field.
func RawTextIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldIn(FieldRawText, vs...))
}

// RawTextNotIn applies the NotIn predicate on the "raw_text" field.
func RawTextNotIn(vs ...string) predicate.Slot {
	return predicate.Slot(sql.FieldNotIn(FieldRawText, vs...))
}

// RawTextGT applies the GT predicate on the "raw_text" field.
func RawTextGT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGT(FieldRawText, v))
}

// RawTextGTE applies the GTE predicate on the "raw_text" field.
func RawTextGTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldGTE(FieldRawText, v))
}

// RawTextLT applies the LT predicate on the "raw_text" field.
func RawTextLT(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLT(FieldRawText, v))
}

// RawTextLTE applies the LTE predicate on the "raw_text" field.
func RawTextLTE(v string) predicate.Slot {
	return predicate.Slot(sql.FieldLTE(FieldRawText, v))
}

// RawTextContains applies the Contains predicate on the "raw_text" field.
func RawTextContains(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContains(FieldRawText, v))
}

// RawTextHasPrefix applies the HasPrefix predicate on the "raw_text" field.
func RawTextHasPrefix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasPrefix(FieldRawText, v))
}

// RawTextHasSuffix applies the HasSuffix predicate on the "raw_text" field.
func RawTextHasSuffix(v string) predicate.Slot {
	return predicate.Slot(sql.FieldHasSuffix(FieldRawText, v))
}

// RawTextIsNil applies the IsNil predicate on the "raw_text" field.
func RawTextIsNil() predicate.Slot {
	return predicate.Slot(sql.FieldIsNull(FieldRawText))
}

// RawTextNotNil applies the NotNil predicate on the "raw_text" field.
func RawTextNotNil() predicate.Slot {
	return predicate.Slot(sql.FieldNotNull(FieldRawText))
}

// RawTextEqualFold applies the EqualFold predicate on the "raw_text" field.
func RawTextEqualFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldEqualFold(FieldRawText, v))
}

// RawTextContainsFold applies the ContainsFold predicate on the "raw_text" field.
func RawTextContainsFold(v string) predicate.Slot {
	return predicate.Slot(sql.FieldContainsFold(FieldRawText, v))
}

// ScrapedAtEQ applies the EQ predicate on the "scraped_at" field.
func ScrapedAtEQ(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldEQ(FieldScrapedAt, v))
}

// ScrapedAtNEQ applies the NEQ predicate on the "scraped_at" field.
func ScrapedAtNEQ(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldNEQ(FieldScrapedAt, v))
}

// ScrapedAtIn applies the In predicate on the "scraped_at" field.
func ScrapedAtIn(vs ...time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldIn(FieldScrapedAt, vs...))
}

// ScrapedAtNotIn applies the NotIn predicate on the "scraped_at" field.
func ScrapedAtNotIn(vs ...time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldNotIn(FieldScrapedAt, vs...))
}

// ScrapedAtGT applies the GT predicate on the "scraped_at" field.
func ScrapedAtGT(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldGT(FieldScrapedAt, v))
}

// ScrapedAtGTE applies the GTE predicate on the "scraped_at" field.
func ScrapedAtGTE(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldGTE(FieldScrapedAt, v))
}

// ScrapedAtLT applies the LT predicate on the "scraped_at" field.
func ScrapedAtLT(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldLT(FieldScrapedAt, v))
}

// ScrapedAtLTE applies the LTE predicate on the "scraped_at" field.
func ScrapedAtLTE(v time.Time) predicate.Slot {
	return predicate.Slot(sql.FieldLTE(FieldScrapedAt, v))
}

// HasFacility applies the HasEdge predicate on the "facility" edge.
func HasFacility() predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FacilityTable, FacilityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFacilityWith applies the HasEdge predicate on the "facility" edge with a given conditions (other predicates).
func HasFacilityWith(preds ...predicate.Facility) predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := newFacilityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMunicipality applies the HasEdge predicate on the "municipality" edge.
func HasMunicipality() predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MunicipalityTable, MunicipalityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMunicipalityWith applies the HasEdge predicate on the "municipality" edge with a given conditions (other predicates).
func HasMunicipalityWith(preds ...predicate.Municipality) predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := newMunicipalityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGround applies the HasEdge predicate on the "ground" edge.
func HasGround() predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroundTable, GroundColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroundWith applies the HasEdge predicate on the "ground" edge with a given conditions (other predicates).
func HasGroundWith(preds ...predicate.Ground) predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := newGroundStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotifications applies the HasEdge predicate on the "notifications" edge.
func HasNotifications() predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationsWith applies the HasEdge predicate on the "notifications" edge with a given conditions (other predicates).
func HasNotificationsWith(preds ...predicate.Notification) predicate.Slot {
	return predicate.Slot(func(s *sql.Selector) {
		step := newNotificationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Slot) predicate.Slot {
	return predicate.Slot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Slot) predicate.Slot {
	return predicate.Slot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Slot) predicate.Slot {
	return predicate.Slot(sql.NotPredicates(p))
}
