// Code generated by ent, DO NOT EDIT.

package ground

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ground type in the database.
	Label = "ground"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMunicipalityID holds the string denoting the municipality_id field in the database.
	FieldMunicipalityID = "municipality_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCourtPattern holds the string denoting the court_pattern field in the database.
	FieldCourtPattern = "court_pattern"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMunicipality holds the string denoting the municipality edge name in mutations.
	EdgeMunicipality = "municipality"
	// EdgeSlots holds the string denoting the slots edge name in mutations.
	EdgeSlots = "slots"
	// Table holds the table name of the ground in the database.
	Table = "grounds"
	// MunicipalityTable is the table that holds the municipality relation/edge.
	MunicipalityTable = "grounds"
	// MunicipalityInverseTable is the table name for the Municipality entity.
	// It exists in this package in order to avoid circular dependency with the "municipality" package.
	MunicipalityInverseTable = "municipalities"
	// MunicipalityColumn is the table column denoting the municipality relation/edge.
	MunicipalityColumn = "municipality_id"
	// SlotsTable is the table that holds the slots relation/edge.
	SlotsTable = "slots"
	// SlotsInverseTable is the table name for the Slot entity.
	// It exists in this package in order to avoid circular dependency with the "slot" package.
	SlotsInverseTable = "slots"
	// SlotsColumn is the table column denoting the slots relation/edge.
	SlotsColumn = "ground_id"
)

// Columns holds all SQL columns for ground fields.
var Columns = []string{
	FieldID,
	FieldMunicipalityID,
	FieldName,
	FieldCourtPattern,
	FieldEnabled,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MunicipalityIDValidator is a validator for the "municipality_id" field. It is called by the builders before save.
	MunicipalityIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Ground queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMunicipalityID orders the results by the municipality_id field.
func ByMunicipalityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMunicipalityID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCourtPattern orders the results by the court_pattern field.
func ByCourtPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCourtPattern, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMunicipalityField orders the results by municipality field.
func ByMunicipalityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMunicipalityStep(), sql.OrderByField(field, opts...))
	}
}

// BySlotsCount orders the results by slots count.
func BySlotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSlotsStep(), opts...)
	}
}

// BySlots orders the results by slots terms.
func BySlots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSlotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMunicipalityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MunicipalityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MunicipalityTable, MunicipalityColumn),
	)
}
func newSlotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SlotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SlotsTable, SlotsColumn),
	)
}
