// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Facility struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	Municipality string    `json:"municipality"`
	ScraperType  string    `json:"scraper_type"`
	Url          string    `json:"url"`
	Enabled      int64     `json:"enabled"`
	CreatedAt    time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Notification struct {
	ID               string     `json:"id"`
	TeamID           string     `json:"team_id"`
	WatchConditionID string     `json:"watch_condition_id"`
	SlotID           string     `json:"slot_id"`
	Channel          string     `json:"channel"`
	Status           string     `json:"status"`
	SentAt           *time.Time `json:"sent_at"`
	CreatedAt        time.Time  `json:"created_at"`
}

type ScrapeJob struct {
	ID           string     `json:"id"`
	FacilityID   string     `json:"facility_id"`
	Status       string     `json:"status"`
	SlotsFound   *int64     `json:"slots_found"`
	ErrorMessage *string    `json:"error_message"`
	StartedAt    *time.Time `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

type Slot struct {
	ID         string    `json:"id"`
	FacilityID string    `json:"facility_id"`
	SlotDate   time.Time `json:"slot_date"`
	TimeFrom   string    `json:"time_from"`
	TimeTo     string    `json:"time_to"`
	CourtName  *string   `json:"court_name"`
	RawText    *string   `json:"raw_text"`
	ScrapedAt  time.Time `json:"scraped_at"`
}

type SupportMessage struct {
	ID        string    `json:"id"`
	TicketID  string    `json:"ticket_id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type SupportTicket struct {
	ID            string    `json:"id"`
	TeamID        *string   `json:"team_id"`
	Email         string    `json:"email"`
	Subject       string    `json:"subject"`
	Status        string    `json:"status"`
	Priority      string    `json:"priority"`
	AiResponse    *string   `json:"ai_response"`
	HumanResponse *string   `json:"human_response"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type SystemMetric struct {
	ID          int64     `json:"id"`
	MetricName  string    `json:"metric_name"`
	MetricValue float64   `json:"metric_value"`
	RecordedAt  time.Time `json:"recorded_at"`
}

type Team struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Plan      string    `json:"plan"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

type WatchCondition struct {
	ID         string     `json:"id"`
	TeamID     string     `json:"team_id"`
	FacilityID string     `json:"facility_id"`
	DaysOfWeek string     `json:"days_of_week"`
	TimeFrom   string     `json:"time_from"`
	TimeTo     string     `json:"time_to"`
	DateFrom   *time.Time `json:"date_from"`
	DateTo     *time.Time `json:"date_to"`
	Enabled    int64      `json:"enabled"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}
