// Code generated by ent, DO NOT EDIT.

package team

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the team type in the database.
	Label = "team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPlan holds the string denoting the plan field in the database.
	FieldPlan = "plan"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStripeCustomerID holds the string denoting the stripe_customer_id field in the database.
	FieldStripeCustomerID = "stripe_customer_id"
	// FieldStripeSubscriptionID holds the string denoting the stripe_subscription_id field in the database.
	FieldStripeSubscriptionID = "stripe_subscription_id"
	// FieldBillingInterval holds the string denoting the billing_interval field in the database.
	FieldBillingInterval = "billing_interval"
	// FieldCurrentPeriodEnd holds the string denoting the current_period_end field in the database.
	FieldCurrentPeriodEnd = "current_period_end"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeWatchConditions holds the string denoting the watch_conditions edge name in mutations.
	EdgeWatchConditions = "watch_conditions"
	// EdgeNotifications holds the string denoting the notifications edge name in mutations.
	EdgeNotifications = "notifications"
	// EdgeAuthTokens holds the string denoting the auth_tokens edge name in mutations.
	EdgeAuthTokens = "auth_tokens"
	// EdgeSupportTickets holds the string denoting the support_tickets edge name in mutations.
	EdgeSupportTickets = "support_tickets"
	// EdgePromoCodeUsages holds the string denoting the promo_code_usages edge name in mutations.
	EdgePromoCodeUsages = "promo_code_usages"
	// Table holds the table name of the team in the database.
	Table = "teams"
	// WatchConditionsTable is the table that holds the watch_conditions relation/edge.
	WatchConditionsTable = "watch_conditions"
	// WatchConditionsInverseTable is the table name for the WatchCondition entity.
	// It exists in this package in order to avoid circular dependency with the "watchcondition" package.
	WatchConditionsInverseTable = "watch_conditions"
	// WatchConditionsColumn is the table column denoting the watch_conditions relation/edge.
	WatchConditionsColumn = "team_id"
	// NotificationsTable is the table that holds the notifications relation/edge.
	NotificationsTable = "notifications"
	// NotificationsInverseTable is the table name for the Notification entity.
	// It exists in this package in order to avoid circular dependency with the "notification" package.
	NotificationsInverseTable = "notifications"
	// NotificationsColumn is the table column denoting the notifications relation/edge.
	NotificationsColumn = "team_id"
	// AuthTokensTable is the table that holds the auth_tokens relation/edge.
	AuthTokensTable = "auth_tokens"
	// AuthTokensInverseTable is the table name for the AuthToken entity.
	// It exists in this package in order to avoid circular dependency with the "authtoken" package.
	AuthTokensInverseTable = "auth_tokens"
	// AuthTokensColumn is the table column denoting the auth_tokens relation/edge.
	AuthTokensColumn = "team_id"
	// SupportTicketsTable is the table that holds the support_tickets relation/edge.
	SupportTicketsTable = "support_tickets"
	// SupportTicketsInverseTable is the table name for the SupportTicket entity.
	// It exists in this package in order to avoid circular dependency with the "supportticket" package.
	SupportTicketsInverseTable = "support_tickets"
	// SupportTicketsColumn is the table column denoting the support_tickets relation/edge.
	SupportTicketsColumn = "team_id"
	// PromoCodeUsagesTable is the table that holds the promo_code_usages relation/edge.
	PromoCodeUsagesTable = "promo_code_usages"
	// PromoCodeUsagesInverseTable is the table name for the PromoCodeUsage entity.
	// It exists in this package in order to avoid circular dependency with the "promocodeusage" package.
	PromoCodeUsagesInverseTable = "promo_code_usages"
	// PromoCodeUsagesColumn is the table column denoting the promo_code_usages relation/edge.
	PromoCodeUsagesColumn = "team_id"
)

// Columns holds all SQL columns for team fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPlan,
	FieldStatus,
	FieldStripeCustomerID,
	FieldStripeSubscriptionID,
	FieldBillingInterval,
	FieldCurrentPeriodEnd,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Plan defines the type for the "plan" enum field.
type Plan string

// PlanFree is the default value of the Plan enum.
const DefaultPlan = PlanFree

// Plan values.
const (
	PlanFree     Plan = "free"
	PlanPersonal Plan = "personal"
	PlanPro      Plan = "pro"
	PlanOrg      Plan = "org"
)

func (pl Plan) String() string {
	return string(pl)
}

// PlanValidator is a validator for the "plan" field enum values. It is called by the builders before save.
func PlanValidator(pl Plan) error {
	switch pl {
	case PlanFree, PlanPersonal, PlanPro, PlanOrg:
		return nil
	default:
		return fmt.Errorf("team: invalid enum value for plan field: %q", pl)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusPaused    Status = "paused"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusPaused, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("team: invalid enum value for status field: %q", s)
	}
}

// BillingInterval defines the type for the "billing_interval" enum field.
type BillingInterval string

// BillingIntervalMonthly is the default value of the BillingInterval enum.
const DefaultBillingInterval = BillingIntervalMonthly

// BillingInterval values.
const (
	BillingIntervalMonthly BillingInterval = "monthly"
	BillingIntervalYearly  BillingInterval = "yearly"
)

func (bi BillingInterval) String() string {
	return string(bi)
}

// BillingIntervalValidator is a validator for the "billing_interval" field enum values. It is called by the builders before save.
func BillingIntervalValidator(bi BillingInterval) error {
	switch bi {
	case BillingIntervalMonthly, BillingIntervalYearly:
		return nil
	default:
		return fmt.Errorf("team: invalid enum value for billing_interval field: %q", bi)
	}
}

// OrderOption defines the ordering options for the Team queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPlan orders the results by the plan field.
func ByPlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlan, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStripeCustomerID orders the results by the stripe_customer_id field.
func ByStripeCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCustomerID, opts...).ToFunc()
}

// ByStripeSubscriptionID orders the results by the stripe_subscription_id field.
func ByStripeSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeSubscriptionID, opts...).ToFunc()
}

// ByBillingInterval orders the results by the billing_interval field.
func ByBillingInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingInterval, opts...).ToFunc()
}

// ByCurrentPeriodEnd orders the results by the current_period_end field.
func ByCurrentPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPeriodEnd, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByWatchConditionsCount orders the results by watch_conditions count.
func ByWatchConditionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWatchConditionsStep(), opts...)
	}
}

// ByWatchConditions orders the results by watch_conditions terms.
func ByWatchConditions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWatchConditionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNotificationsCount orders the results by notifications count.
func ByNotificationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationsStep(), opts...)
	}
}

// ByNotifications orders the results by notifications terms.
func ByNotifications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuthTokensCount orders the results by auth_tokens count.
func ByAuthTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthTokensStep(), opts...)
	}
}

// ByAuthTokens orders the results by auth_tokens terms.
func ByAuthTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySupportTicketsCount orders the results by support_tickets count.
func BySupportTicketsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSupportTicketsStep(), opts...)
	}
}

// BySupportTickets orders the results by support_tickets terms.
func BySupportTickets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSupportTicketsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPromoCodeUsagesCount orders the results by promo_code_usages count.
func ByPromoCodeUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPromoCodeUsagesStep(), opts...)
	}
}

// ByPromoCodeUsages orders the results by promo_code_usages terms.
func ByPromoCodeUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromoCodeUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newWatchConditionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WatchConditionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WatchConditionsTable, WatchConditionsColumn),
	)
}
func newNotificationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
	)
}
func newAuthTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AuthTokensTable, AuthTokensColumn),
	)
}
func newSupportTicketsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SupportTicketsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SupportTicketsTable, SupportTicketsColumn),
	)
}
func newPromoCodeUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromoCodeUsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PromoCodeUsagesTable, PromoCodeUsagesColumn),
	)
}
